### ISSUE TITLE
[Hunter] Lupos doesn't do shadow damage when tamed

### ISSUE THREAD

**Issue by HungryGrasshopper** [HateForge-WoW/Bugtracker#100]
**Fehlerbeschreibung**
Back in vanilla WoW, Lupos was known to do shadow damage when tamed. This was changed in patch 1.9, but the server is at patch 1.5.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Tame Lupos as a hunter.
2. Command him to attack a mob.
3. Observe that the combat log says "Lupos hits Defias Pillager for 25".

**Erwartetes Verhalten**
Lupos should be doing shadow damage, and the combat log should read "Lupos does hits Defias Pillager for 25 shadow damage".

**Screenshots**
![Lupos](https://github.com/HateForge-WoW/Bugtracker/assets/13590161/feb808bc-8c8a-4e3a-b62b-e92c6c106aac)

**Quellenangabe**
The patchnotes can be found at https://wowwiki-archive.fandom.com/wiki/Patch_1.9.0
I have included a screenshot of the relevant portion of the patchnotes:
![patch 1 9](https://github.com/HateForge-WoW/Bugtracker/assets/13590161/dd166fff-cfe9-4aaf-a314-1de19ddfedcd)

**Comment by VincentADK** [comment]
Hey there!
We are currently on patch 1.5 and the information that you have layed out is completely correct. 
However from the start we had Lupos on his post nerf stage, this means he will not do any Shadow damage what so ever. 
We have certain features like the mount system, the taxi notes and Lupos for example on the 1.12. stage of the game. 
I hope this clarifies it! Have a good one and thank you very much for submitting tickets in the first place!
Have an awesome day and take care! :D
