### ISSUE TITLE
Quest "Plagued Lands" ist verbuggt

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#111]
**Fehlerbeschreibung**
In dieser Quest soll man einen "Rabid Thistle Bear" einfangen. Hierfür kriegt man eine Falle die man benutzen muss, und dann muss man solch einen Bären in die Nähe der Falle ziehen. Wenn man dies getan hat ist die Quest erledigt. Jedoch geht dies hier nicht. Ich habe versucht den Bären zu verletzten bis er fast tot war und habe auch die Quest gelöscht und wieder angenommen. Dies hat jedoch nichts geändert.

**Zur Reproduktion**
Gehe nach Auberdine (Darkshore) und nehme die Quest "Plagued Lands" an, und versuche diese abzuschließen.

**Erwartetes Verhalten**
Wie oben beschrieben sollte es reichen die Falle, also den Gegenstand den man vom Questgeber bekommt zu benutzen, und einen "Rabid Thistle Bear" in die Nähe zu bringen um diesen zu fangen.

**Screenshots**
Hier sind 2 Videos, wo man sieht das es nicht geht:
[https://streamable.com/zbsmo8](url)
[https://streamable.com/ykf08e](url)

**Quellenangabe**
Hier ist ein Link mit Video von Wowhead (Classic WoW): https://www.wowhead.com/classic/quest=2118/plagued-lands

**Zusätzlicher Kontext**
(Bitte die Videos ansehen)

**Comment by ratkosrb** [comment]
![WoWScrnShot_112023_115829](https://github.com/HateForge-WoW/Bugtracker/assets/35845488/55969fcd-7018-4872-addf-4127c6adff75)

Cannot reproduce the issue on clean vmangos. Must be specific to this server.

**Comment by schell244** [comment]
Could not reproduce as well. Tested with a warrior and also with hunter + pet for potential edge case. Both worked for me.
![WoWScrnShot_112023_190019](https://github.com/HateForge-WoW/Bugtracker/assets/9536270/bf1a65e7-6cd4-4682-b49e-1e6aff5f3d7a)

**Comment by VincentADK** [comment]
Scheint wieder zu funktionieren, ich hatte diese Quest vor unseren großen 1.2 Update gemacht. Scheint wohl dadurch gefixt worden zu sein. Hier 2 Videos mit Pet und ohne Pet drausen: 
https://streamable.com/2uynyy
https://streamable.com/6q337e
