### ISSUE TITLE
Warlock Dunkler Pakt Manaausbeute

### ISSUE THREAD

**Issue by Dasore** [HateForge-WoW/Bugtracker#112]
Dunkler Pakt vom "Gebrechen" Lock zieht bei Lvl 1 nur 150 Mana und Lvl 2 nur 200 Mana vom Pet auf den Lock. Da das Mana nur transferiert wird, wäre eine höhere Grundausbeute bzw eine Anrechnung vom Spell/Shadowspelldmg sinnvoll.

**Comment by VincentADK** [comment]
Hallo Dasore! Vielen lieben Dank!

Wir schauen mal was wir tun können, der Spell ist sehr tief verankert. 
Ich schließe das hier mal, danke nochmals! Machs gut! :D
