### ISSUE TITLE
Sinn von Seelensplittertaschen

### ISSUE THREAD

**Issue by Dasore** [HateForge-WoW/Bugtracker#113]
Stapelgröße von Seelensplittern in Splittertaschen erhöhen, ansonsten sind die ja total sinnlos. 

Bei 5er Stapel in der normalen Tasche würde nie jemand nen Platz für ne Splittertasche aufgeben.

Alternativ Stapelgröße auf 1 in normalen Bags und auf 5? 10? in Splittertaschen.

**Comment by VincentADK** [comment]
Hallo Dasore, vielen lieben Dank für deinen Vorschlag!

Wir haben diesen intern besprochen und dafür würden wir eine Klient Modifikation benötigen, ist also gerade nicht möglich. Ist halt client sided. Ich danke dir dennoch! Werde das mal hier schließen! :D
