### ISSUE TITLE
Trainingspuppen in SW geben Skillpunkte

### ISSUE THREAD

**Issue by Rukachi** [HateForge-WoW/Bugtracker#114]
**Fehlerbeschreibung**
Die Trainingspuppen in SW geben Skillpunkte für die angelegte Waffe.

**Zur Reproduktion**
Schlachtzugspuppe anhauen.

**Erwartetes Verhalten**
Da Classic sonst keine training dummys hatte, wird dieser einfache Weg so nicht gewollt sein.

**Comment by VincentADK** [comment]
Hallo Rukachi, vielen lieben Dank für deinen Post!
Das ist in der Tat gewollt, ist also somit kein Bug. Dies soll einfach dazu dienen es etwas einfacher zu machen mit dem Waffen trainieren. Ich wünsche dir noch einen schönen Tag und bis zum nächsten mal! :)
