### ISSUE TITLE
[Schurke] Kopfnuss kann Gifte proccen

### ISSUE THREAD

**Issue by Smilez4U** [HateForge-WoW/Bugtracker#118]
**Fehlerbeschreibung**
Kopfnuss kann Gifte proccen. Im Fall vom Sofort wirkendes Gift kommt der Mob direkt aus dem CC raus.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Sofort wirkendes Gift auf Waffe haben
2. Mob sappen
3. Siehe Fehler

**Erwartetes Verhalten**
Kopfnuss sollte keine Gifte proccen können. Gifte sollten nur von "white hits" und "direct damage" Fähigkeiten, die Combopunkte generieren, proccen.

**Comment by ratkosrb** [comment]
You are wrong. It is blizzlike for Sap or any other ability that requires a melee weapon to apply poisons.

Here is proof from original vanilla.
https://www.youtube.com/watch?v=klMsyF_Kz5o

Here is post from Blizzard's forums of players complaining about the same thing.
https://us.forums.blizzard.com/en/wow/t/sap-applies-poisons/309762

**Comment by Smilez4U** [comment]
My mistake.
I'd like to change this bug report to a suggestion then if possible.

**Comment by VincentADK** [comment]
Same reason as this one: https://github.com/HateForge-WoW/Bugtracker/issues/119
We discussed this internally and came to the conclusion that we don't want to change it, as in want it to be Blizzlike. 
Thank you for your report and suggestion tho! 
Have a good one and thanks again! <3
