### ISSUE TITLE
[Schurke] Vorschlag, dass Solarplexus keine Gifte proccen kann

### ISSUE THREAD

**Issue by Smilez4U** [HateForge-WoW/Bugtracker#119]
**Beschreibe deinen Vorschlag**
Solarplexus kann in Classic Gifte proccen. Das ist aber hinderlich, wenn man Sofort wirkendes Gift oder Tödliches Gift auf der Waffe hat, da der CC dann direkt abbricht. Deswegen der Vorschlag, dass Solarplexus keine Gifte mehr proccen kann.

**Zusätzlicher Kontext**
Es wurde erst mit Patch 2.1.0 geändert.
[Ability Gouge: This ability will no longer trigger poisons (and thus break itself).](https://wowpedia.fandom.com/wiki/Patch_2.1.0)

**Comment by VincentADK** [comment]
Hallo Smilez, vielen lieben Dank!
Wir haben deinen Vorschlag intern besprochen. Wir ändern erst einmmal nichts an dem System. Es ist Blizzlike und so würden wir es gerne haben. Was man machen könnte ist auf der Mainhand-Waffe Crippling Poison zu verwenden anstatt ein Gift das Schaden macht. Dennoch danke ich dir! Ich werde das hier mal schließen. Machs gut! :D
