### ISSUE TITLE
Hord Ony Prequest - Befehl des Kriegsherrn 

### ISSUE THREAD

**Issue by Dreikaesehoe** [HateForge-WoW/Bugtracker#121]
**Fehlerbeschreibung**
Um die Onypre-Quest zu starten muss man einfach nur [Kriegsherr Goretooth](https://www.wowhead.com/classic/de/npc=9077/kriegsherr-goretooth) ansprechen.

Dieser gibt kein quest Sondern ein Brief (Befehl des Kriegsherrn), der das gleichnamige Quest startet in das Inventar des Charakters.

Leider hat mir Kriegsherr Goretooth nicht ins Inventar gegeben. Ein GM musste mir den Brief ins Inventar erstellen. 

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Gehe zu 'Kriegsherr Goretooth.' als Horde
2. Klicke auf 'Kriegsherr Goretooth um mit ihm zu sprechen ab lvl 55'
3. Siehe Fehler

**Erwartetes Verhalten**
Sprich Kriegsherr Goretooth an - Brief im Inventar 

**Screenshots**
Füge gegebenenfalls Screenshots hinzu, um das Problem zu verdeutlichen.

**Quellenangabe**
Um das Problem lösen zu können, müssen wir die Richtigkeit des "Erwartetes Verhalten" anhand von offiziellen Quellen prüfen. Füge einen Link zu einer offiziellen Quelle hinzu.

**Zusätzlicher Kontext**
Falls vorhanden, füge hier weitere Informationen zum Problem hinzu.

**Comment by schell244** [comment]
Wurde die pre-quest abgeschlossen?
https://www.wowhead.com/classic/item=12563/warlord-goretooths-command#comments
_Disharmony of the flame is what the pre-quest is called for the horde. Starts in kargath, badlands._
https://www.wowhead.com/classic/quest=3906

**Comment by schell244** [comment]
Es wird die pre-quest benötigt, desweiteren muss der Ruf bei Orgrimmar mindestends auf freundlich sein. Dann erscheint der Gossip und man bekommt den Brief (Befehl des Kriegsherrn)
