### ISSUE TITLE
Burg Shadowfang

### ISSUE THREAD

**Issue by Milo-Mio** [HateForge-WoW/Bugtracker#122]
Wir kommen nicht zu dem NPC der uns den Innenhof aufsperrt. Die Fackeln lassen sich anklicken, aber es passiert nichts.
Wir haben die Instanz auch schon resettet. Gleiches Problem mit anderem Leader.

![Bildschirmfoto 2023-11-19 um 15 53 09](https://github.com/HateForge-WoW/Bugtracker/assets/151452029/32954c2c-1159-4cb0-9d3f-c0b2a0bc0c3e)

**Comment by VincentADK** [comment]
Kann ich bestätigen, beim aktivieren der Fackel ist nichts passiert. Da müssen wir unbedingt mal nachschauen. :D
Danke für den Bugreport!

**Comment by schell244** [comment]
Fix kommt mit dem nächsten update. Danke für den Report!
