### ISSUE TITLE
Geschundene Dämonenhaut aus Desolace startet keine Quest

### ISSUE THREAD

**Issue by nn-23** [HateForge-WoW/Bugtracker#123]
Geschundene Dämonenhaut aus Desolace startet keine Quest

Ist ein L25 Item, Seelengebunden, tut aber nichts.

https://www.wowhead.com/classic/de/item=20310/geschundene-dämonenhaut#english-comments](https://www.wowhead.com/classic/de/item=20310/geschundene-d%C3%A4monenhaut#english-comments

Danke für euren unermüdlichen Einsatz hier :)

**Comment by nn-23** [comment]
![grafik](https://github.com/HateForge-WoW/Bugtracker/assets/21192997/3f65d41b-679d-45b7-9e1c-7215aff122fb)

**Comment by schell244** [comment]
Fix kommt mit dem nächsten update, danke für den Report!
