### ISSUE TITLE
Urok Schreckensbote lässt sich nicht beschwören - LBRS

### ISSUE THREAD

**Issue by Texhon** [HateForge-WoW/Bugtracker#124]
**Fehlerbeschreibung**
Der Boss Urok Schreckensbote lässt sich nicht in LBRS beschwören.
Es werden der Kopf von Omokk sowie eine beschlagene Pieke benötigt. Beides muss an Uroks Tributhaufen benutzt werden, das funktioniert hier allerdings nicht. Der Charakter sagt nur "Ich muss etwas anvisieren".

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Lower Blackrock Spire - Pike looten & Omokk umhauen + Kopf looten
2. Den Kopf bei Tributhaufen benutzen
3. Lässt sich nicht benutzen

**Erwartetes Verhalten**
Item benutzen, und mehrere Wellen an Elite Ogern beschwören bis der Boss spawnt.

**Screenshots**
Füge gegebenenfalls Screenshots hinzu, um das Problem zu verdeutlichen.

**Quellenangabe**
https://www.wowhead.com/classic/de/npc=10584/urok-schreckensbote#english-comments;mode:normal
https://www.youtube.com/watch?v=21HBjqWu6dg

**Zusätzlicher Kontext**
Falls vorhanden, füge hier weitere Informationen zum Problem hinzu.

**Comment by ratkosrb** [comment]
Fix https://github.com/vmangos/core/commit/7168faf7228690db1cd5a724d8ddba60bcc4e2fe

**Comment by schell244** [comment]
Thanks a lot @ratkosrb. Fix applied and confirmed!
