### ISSUE TITLE
Schlachtfeld: Buffanzeige

### ISSUE THREAD

**Issue by Rukachi** [HateForge-WoW/Bugtracker#125]
**Beschreibe deinen Vorschlag**
Die Buffs in den Schlachtfeldern, die man einsammeln kann (Berserker, Schnelligkeit, Heal), werden im Debuff-Fenster angezeigt. Das hat zur Folge, dass man die wieder verliert, wenn man Bubble benutzt. Auch kann man die erst gar nicht einsammeln, wenn man vorher schon mit Bubble drüber läuft. 

Vorschlag= In dem Buff-Fenster, wo auch die anderen Spielerbuffs sind, positionieren

**Zusätzlicher Kontext**
https://www.wowhead.com/classic/de/spell=23505/berserker
https://www.wowhead.com/classic/de/spell=23451/geschwindigkeit
https://www.wowhead.com/classic/de/spell=23493/wiederherstellung

**Comment by VincentADK** [comment]
Hallo Rukachi, danke für deinen Beitrag!
Wir haben dies hier intern besprochen und wir lassen es erst einmal so wie es ist. 
Ganz einfach weil es Blizzlike ist und es könnte auch super OP sein mit der Bubble einen Speedboost zu haben usw.
Ich schließe das hier mal, dennoch vielen lieben Dank! :D
