### ISSUE TITLE
Schlachtfeld: Level der Bot-Spieler

### ISSUE THREAD

**Issue by Rukachi** [HateForge-WoW/Bugtracker#126]
**Beschreibe deinen Vorschlag**

Low lvl Gegner geben einem keinen Ehrenhaften Sieg. Als 29er bringt mir der Kill eines Bots ab 22 und niedriger nichts mehr. 
Ein Bot-Spiel ist schon ärgerlich aber dann mit angepasstem Gegner-Level, dass der Kill auch einen Vorteil hat. 

Es sind nicht alle Bot-Gegner im BG so niedrig, dass die einem nichts bringen aber zwischendurch sind da welche dabei. 

Vorschlag = Bots so anpassen, dass die dem Spieler einen Ehrenhaften Sieg verschaffen.

**Comment by VincentADK** [comment]
Hallo, vielen lieben Dank für das Feedback und deinen Vorschlag!
Wir haben das hier intern besprochen und sind zu dem Entschluss gekommen, dass wir hier dran, erst einmal nichts ändern werden. Die Brackets sind Blizzlike, dass wäre also auch mit richtigen Spielern so. Ich schließe das hier mal. Dennoch vielen lieben Dank! :D
