### ISSUE TITLE
Magier: Verwandlung Schwein

### ISSUE THREAD

**Issue by sandmann12** [HateForge-WoW/Bugtracker#127]
Die Magier Bots am Schlachtfeld haben den Zauber Verwandlung:Schwein!

Leider  fehlt die Quest für  uns Magier in Azshara!

**Comment by VincentADK** [comment]
Hier sind die fehlenden Quellen: https://www.wowhead.com/classic/de/npc=8379/erzmagier-xylem
https://www.wowhead.com/classic/de/quest=9364/gespaltene-magie

**Comment by Texhon** [comment]
Auf dem PTR hat es funktioniert gehabt. Startquest ist "Kriegsherr Krellian" von Erzmagier Xylem in Azshara
https://www.wowhead.com/classic/de/quest=9362/kriegsherr-krellian
