### ISSUE TITLE
Kaputte Maps in Ashenvale (The Dor'Danil Barrow Den)

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#128]
**Fehlerbeschreibung**
Bitte schaue dir die Screenshots an. An dem bestimmten Punkt [](https://i.imgur.com/rapLN4S.png) unten in den Barrows können Gegner und Pets nicht drüber laufen, es wäre so als ob dort eine Wand wäre, bzw. die Map kaputt wäre. Die Mobs bzw. Pets laufen durch das ganze Teil um auf die andere Seite zu gelangen, dabei kann man da eigentlich ganz normal drüber laufen.

**Zur Reproduktion**
Siehe oben.

**Erwartetes Verhalten**
Man sollte dort normal drüber laufen können, da sollte Mobs und Pets beinhalten. 

**Screenshots**
https://imgur.com/a/EaJqt4F

**Comment by schell244** [comment]
Sollte behoben sein, gerne nochmal nachtesten.
