### ISSUE TITLE
RFD Boss Glutton scheint eine (Kaputte) Stealth Mechanik zu haben laut Discord.

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#130]
**Fehlerbeschreibung**
Ich schreibe das hier da die Bugreports noch nicht erstellt wurden sind.
Hier sind ein paar Zitate: "Ach und ja, Glutton ist auch bei 2/2 runs plötzlich aus dem stealth gekommen und hat uns quasi geambushed ^^"
"und natürlich der dicke Boss im Gang, der plötzlich aus dem Stealth die Gruppe untoter jointe"

**Zur Reproduktion**
 Selbsterklärend.

**Erwartetes Verhalten**
 Selbsterklärend.
(Sollte so nicht passieren.)

**Screenshots**
Keine.

**Quellenangabe**
https://www.wowhead.com/classic/guide/razorfen-downs-dungeon-strategy-wow-classic#glutton
https://www.wowhead.com/classic/npc=8567/glutton#abilities;mode:normal

**Zusätzlicher Kontext**
Keine.

**Comment by schell244** [comment]
War ein Problem der maps, sollte nun behoben sein. Danke fürs Melden!
