### ISSUE TITLE
Timbermaw Hold Rep Quest Items (Federn) droppen nicht

### ISSUE THREAD

**Issue by 19Samael96** [HateForge-WoW/Bugtracker#133]
Laut einigen aussagen von guildmates droppen die federn für die timbermaw hold repeatable rep-quest nicht.

**Zur Reproduktion**
Sollte selbsterklärend sein, bzw leicht rauszufinden ob die federn im loottable sind.

**Comment by UHGuezel** [comment]
Einer der Guildmates hier. 
Habe auf Lux heute schon locker 60 von den Furbolgs weggehauen.
Kein einziger Drop soweit.

Eventuell einfach bad luck oder mieserable Droprate, aber langsam wirds verdächtig. :D

**Comment by schell244** [comment]
Die Droprate wurde erhöht (von 25% auf 50-75%), danke fürs Melden!
