### ISSUE TITLE
Abrechnung/Reckoning vom Paladin sollte einen Buff anzeigen.

### ISSUE THREAD

**Issue by UHGuezel** [HateForge-WoW/Bugtracker#137]
**Beschreibe deinen Vorschlag**
Das Talent "Abrechnung" im Schutz-Baum des Paladins zeigt keinen Buff an. 
Dies ist, soweit ich das aus diversen Videos entnehmen konnte, so gewollt. 
Die Änderung, dass das Talent doch einen Buff anzeigt, würde für mehr visuelle Klarheit, sowohl für den Paladin, als auch für den Gegner (PvP), sorgen. 
Der Paladin kann sich darauf vorbereiten, mit dem nächsten Angriff sehr wehzutun, während der Gegenspieler sich darauf vorbereiten kann, dass der nächste Angriff böse wehtun wird.

**Zusätzlicher Kontext**
[Hier wäre ein Video aus WoW Classic, wo bei Minute 0:15 sehr gut zu sehen ist, dass keine Buffs angezeigt werden und dennoch 5 Autohits aufeinmal ausgelöst werden.](https://www.youtube.com/watch?v=yRVqV6Rdic4)

**Comment by VincentADK** [comment]
Hey, vielen lieben Dank!
Wir haben dies hier intern besprochen und leider benötigt man dafür eine Klient Modifikation, welche im Moment nicht möglich ist. Wir arbeiten and etwas schönen, sollte dann in der Zukunft möglich sein, aber gerade in dem Moment halt leider nicht. Ich schließe das hier mal. Dennoch vielen lieben Dank für dein Feedback und dem Vorschlag!
