### ISSUE TITLE
Quests für die EXP-Trinkets sollten in jeder Stadt zu finden sein!

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#14]
**Beschreibe deinen Vorschlag**
Könnten wir die Quests für Trinkets in jeder Stadt anbieten?

**Zusätzlicher Kontext**
Vorschlag von Shiruxx nur noch mehr ausgedehnt.

**Comment by Nolin7777** [comment]
Abgelehnt.
