### ISSUE TITLE
Ritualtotem der Winterfelle/Totenfelle 

### ISSUE THREAD

**Issue by UHGuezel** [HateForge-WoW/Bugtracker#140]
**Fehlerbeschreibung**
Die Questitems starten keine Quests.

**Zur Reproduktion**

1. Gehe nach Teufelswald und farme die Questitems.
2. Rechtsklick auf Ritualtotem
3. Nichts passiert.

**Erwartetes Verhalten**
Man sollte, wie es bei Questgeberitems üblich ist, eine Quest vorgeschlagen bekommen.

**Zusätzlicher Kontext**
Falls vorhanden, füge hier weitere Informationen zum Problem hinzu.

**Comment by schell244** [comment]
Fix kommt mit dem nächsten Update. Danke für den Report!
