### ISSUE TITLE
Drek'Thar Kill schließt manchmal AV BG nicht ab

### ISSUE THREAD

**Issue by Texhon** [HateForge-WoW/Bugtracker#144]
**Fehlerbeschreibung**
Stellenweise kommt es vor, dass ein Drek'thar Kill im AV nicht gewertet wird und entsprechend das AV BG nicht geschlossen wird. Er spawnt dann nach 1-2 Minuten neu.

**Erwartetes Verhalten**
Drek'thar stirbt und das BG ist vorei.

**Screenshots**
![Drekk_kill1](https://github.com/HateForge-WoW/Bugtracker/assets/145346967/25a2a98a-49af-42c3-ae45-68020f44c773)
![drekk_kill2](https://github.com/HateForge-WoW/Bugtracker/assets/145346967/f3be5506-9c81-4057-a134-f0de2b3e1d44)

**Comment by Texhon** [comment]
https://youtu.be/XitPOdURCy4
Sollte deutlicher sein :)

**Comment by schell244** [comment]
Sollte nach dem nächsten update nicht mehr passieren. Danke für den Report!
