### ISSUE TITLE
Quest: spendet Wolle

### ISSUE THREAD

**Issue by Rukachi** [HateForge-WoW/Bugtracker#146]
**Fehlerbeschreibung**
Quest hat mir beim ersten abgeben von 60 Wolle nur ca 120 XP, mit Erholung (hab die genaue Zahl nicht mehr im Kopf) gegeben. 

**Zur Reproduktion**
Wolle bei Mistina Steelshield, in Ironforge abgeben.

**Erwartetes Verhalten**
Die erste Abgabe sollte deutlich mehr an XP geben. 
Das ganze habe ich mit den anderen Stoffen oder NPCs noch nicht getestet. (Könnte auch auf die anderen zutreffen)

**Quellenangabe**
https://www.wowhead.com/classic/de/quest=7802/spendet-wolle

**Comment by schell244** [comment]
Fix kommt mit dem nächsten Update. Danke für den Report!
