### ISSUE TITLE
Line of Sight bei Zaubern

### ISSUE THREAD

**Issue by xkingdingelingx** [HateForge-WoW/Bugtracker#147]
**Fehlerbeschreibung**
Seit kurzem gibt es einen Fehler bei der Abfrage von Line of Sight bei Zaubern. Habe es nur mit Heilzaubern ausprobiert, denke aber das betrifft alle Zauber. 
Je nachdem wie man steht bekommt man nicht die Meldung "Ziel befindet sich nicht im Sichtfeld", sondern der Zauber geht durch, es wird Mana abgezogen, aber der Heil-Zauber hat 0 Wirkung.

**Zur Reproduktion**
An Rampen / Höhenunterschiede lässt sich das am besten triggern. (z.B. Warsong Vorbereitungsphase die Rampe zum Tunnel, betrifft aber auch Instanzen und die freie Welt).

*Edit: Objekte in der freien Welt/Instanzen sind auch ganz böse. Bsp.: Strath Hintereingang. Ziel und Heiler haben eine Holzkiste zischen sich stehen. Heal wird gecastet, geht durch, kostet mana -> 0 Effekt.* 

Ziel steht oben, Heiler unten an der Rampe direkt vor der Wand = Ziel befindet sich nicht im Sichtfeld

Heiler bewegt sich in die Mitte der Rampe = Heal geht durch, kostet Mana, aber 0 Effekt (Auch Hots, Buffs kommen nicht an, aber kosten Mana)

Heiler geht geht ganz hoch = kann normal heilen, alles passt.

**Erwartetes Verhalten**
Die Abfrage sollte verhindern, dass Zauber überhaupt gewirkt werden können, wenn sich das Ziel eigentlich nicht im Sichtfeld befindet.

**Comment by schell244** [comment]
Das Problem sollte behoben sein. Danke für den Report!
