### ISSUE TITLE
EXP Trinkets für Gold

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#149]
**Beschreibe deinen Vorschlag**
Es wäre vielleicht eine gute Idee das wir die EXP Trinkets auch einfach nur für Gold anbieten könnten. 
Dies würde somit dann auch als weiteren Goldsink dienen.
Die Idee kommt im Endeffekt durch unsere Community, da es etliche Leute gab die sich über das EXP Trinket beschwert hatten.

**Comment by Hordespieler** [comment]
Ja fände ich auch gut, dadurch das es nur für ingis zugänglich ist haben wir absurde Lederpreise und viel zu wenig von quasi allen anderen Berufen.

**Comment by VincentADK** [comment]
Wir haben dies hier intern besprochen und sind zu dem Entschluss gekommen das wir das permanente Trinket nicht abändern werden. Das sollte so passen wie es ist. Das 2 Stunden Trinket wurde von uns aus dem Spiel genommen und mit dem kleinen Gnom ersetzt. Dieser bietet euch umsonst mehr Erfahrung an (2x - 3x). Sollte damit also eigentlich gegessen sein. Ich schließe das mal hier. :D
