### ISSUE TITLE
Gruppenerfahrungsmalus abändern

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#150]
**Beschreibe deinen Vorschlag**
Die Idee kommt durch unsere Community.
Vielleicht sollten wir mal schauen das wir entweder diesen Malus herunterschrauben oder sogar in die andere Richtung gehen sollten. D.h. das man vielleicht sogar mehr Erfahrung bekommen sollte, wenn man sich in einer Gruppe befindet. Dies soll damit helfen das Leute mehr zusammen spielen und miteinander sozialisieren. Das wäre dann auch eine weitere Level-Simplifikation.

**Comment by Hordespieler** [comment]
Das finde ich eigentlich eine Gute Sache, meiner Meinung nach sollte aber nicht für HC Charaktere so umgesetzt werden.

Da HC lvlen in einer Gruppe natürlich viel ungefährlicher ist. Meiner Meinung nach ist HC so wie es ist, perfekt. 

Was soll 4 Mages und einem Priester denn bitte passieren? 

Sollte es nun keine Vorteile mehr bringen alleine zu lvlen oder es sogar Nachteile bringen wäre auch der HC-Erfolg deutlich weniger wertig, da natürlich niemand alleine HC-Lvlen würde.
Im Gegenteil, da die Belohnung für HC auf 60 ein Epic Mount ist könnten man einfach HC Multiboxen, was sehr effektiv wäre. 
Ob ihr das überhaupt so Konfigurieren könnt weiß ich nicht. 

Wenn das aber für HC-Charaktere so umgesetzt wird wie vorgeschlagen, könnt ihr das Feature auch abschalten. 

Ich bitte euch das zu bedenken.

**Comment by VincentADK** [comment]
Sollte nun implementiert sein, also durch den kleinen Gnom. Der gibt einen 2x -3x mehr EXP, somit kriegt man nun auch viel mehr EXP in Gruppen. HC ist davon ausgeschlossen. Ich schließe das mal hier. :D
