### ISSUE TITLE
Blacksmith recipe bug

### ISSUE THREAD

**Issue by ForxTheWarrior** [HateForge-WoW/Bugtracker#153]
When buying recipes from the artisan blacksmith trainer in Ironforge, the recipes won’t be learned but the gold cost will still be taken

**Comment by schell244** [comment]
Unable to reproduce the issue. Checked all blacksmith trainer in Ironforge and was able to learn all recipes. Any additional preconditions to reproduce this?

**Comment by schell244** [comment]
The problem should no longer occur on current version. Thanks for the report!
