### ISSUE TITLE
WSG Qeust Horde 

### ISSUE THREAD

**Issue by Dreikaesehoe** [HateForge-WoW/Bugtracker#156]
**Fehlerbeschreibung**
Eine klare und präzise Beschreibung des Fehlers.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Gehe zu "Mor`shan-Stützpunk im Brachland'
2. Klicke auf '''Captain Shatterskull um die Quest "Bezwingt die Eindringlinge der Silberschwingen anzunehmen"
3. Quest kann man nicht abgeben Obwohl man WSG-Marken im Inventar hat

**Erwartetes Verhalten**
Quest sollte abzugeben sein

**Screenshots**
Füge gegebenenfalls Screenshots hinzu, um das Problem zu verdeutlichen.

**Quellenangabe**
Um das Problem lösen zu können, müssen wir die Richtigkeit des "Erwartetes Verhalten" anhand von offiziellen Quellen prüfen. Füge einen Link zu einer offiziellen Quelle hinzu.

**Zusätzlicher Kontext**
Falls vorhanden, füge hier weitere Informationen zum Problem hinzu.

**Comment by schell244** [comment]
Die Quest benötigte die alte Version der pvp Tokens, bzw die Quest wurde in einem neuen Patch entfernt (siehe https://www.wowhead.com/classic/de/npc=14781/captain-shatterskull - es sind keine quests verlinkt). Danke für den Report! Captain Shatterskull sollte nun keine Quests mehr anbieten.
