### ISSUE TITLE
Rune in Mazthoril

### ISSUE THREAD

**Issue by Dasore** [HateForge-WoW/Bugtracker#159]
**Fehlerbeschreibung**
Die Teleportrune in der Höhle in Mazthoril funktioniert nicht

**Erwartetes Verhalten**
Port aufn Berg?

**Comment by schell244** [comment]
Konnte das Problem nicht reproduzieren, die Rune hat bei mir funktioniert. Gerne nochmal nachtesten. Vielen Dank!
