### ISSUE TITLE
Belohnungen für unsere PTR Tester/Spieler für den live realm

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#16]
**Beschreibe deinen Vorschlag**
Es wäre super wenn wir unseren Leutchen etwas schenken könnten wenn der Server online geht.
Sowas wie Tabards, vielleicht ein Pet usw. so als kleines Dankeschön. 

**Zusätzlicher Kontext**
-

**Comment by Nolin7777** [comment]
Ja, ist etwas geplant! :)

**Comment by Nolin7777** [comment]
Wurde zu dem internen Bugtracker für Diskussionen verschoben.
