### ISSUE TITLE
Keine doppelte Ehreberechnung im Warmode

### ISSUE THREAD

**Issue by Dreikaesehoe** [HateForge-WoW/Bugtracker#160]
**Fehlerbeschreibung**
Warmode ist Aktiv aber nur die normale Ehre wird berechnet.
Die Ehreberechnung ist nicht doppelt wie angekündigt.

- Eine Runde AB gespielt ca. 1053 Ehre durch Kills und 1386 Ehre für den Sieg durch Punkte.
Also genau 2439 Ehre angerechnet bekommen, mit Warmode sollte es 4878 Ehre sein.

**Comment by xkingdingelingx** [comment]
Die doppelte Ehre für den Warmode zählt doch nur in der freien Welt. Wurde meines Wissens nach extra so gemacht, nach einem Vorschlag auf dem PTR.

**Comment by Dreikaesehoe** [comment]
dann stimmt die Homepage nicht... https://de.hateforge.de/de/page/konzept 

und ich würde den Warmode dann bitte wieder abschalten können das wusste ich so nicht und bringt dann in der Openworld nur nachteile weil 99% kein Warmode an haben. 

Das bedeutet man wird nur gegrieft wenn es gerade passt und danach "verpissen" sich die non PVPler wieder und sind dann ungeflaggt.,..

**Comment by xkingdingelingx** [comment]
Woina — 31.10.2023 19:13
"Im Warmode gibt es ab sofort nur noch außerhalb von Schlachtfeldern doppelte Ehrenpunkte."
Das ist super fair und korrekt, danke dafür!

Wurde also irgendwann mal so anounced. Die offizielle Quelle müsste dann in irgendwelchen Patchnotes so mal drin gestanden haben.

**Comment by Woina89** [comment]
https://forum.hateforge.de/viewtopic.php?t=50
You're welcome :-)

**Comment by Dreikaesehoe** [comment]
:D So ein quatsch - schlechte Anpassung, macht 0 Sinn und kommt von einem PVE spieler. Wo kann ich den Warmode dann bitte wieder ausmachen ?!

**Comment by Dreikaesehoe** [comment]
""Woina — 31.10.2023 19:13
"Im Warmode gibt es ab sofort nur noch außerhalb von Schlachtfeldern doppelte Ehrenpunkte."
Das ist super fair und korrekt, danke dafür!"" 

das klingt so ironisch xD  ich bin gerade fassungslos das diese änderung übernommen wurde :D:D

**Comment by Woina89** [comment]
Mein Kommentar war nach der Änderung, und kein Vorschlag :-D

**Comment by VincentADK** [comment]
Hallo, vielen lieben Dank für das Feedback und die Vorschläge!
Wir haben das intern besprochen und werden erst einmal nichts an dem System ändern. 
Bei Nefarian konnte man sich auch den Warmode anschalten, aber dort gab es keinerlei Boni, hier bekommst du 2x Ehre in der Open World.
