### ISSUE TITLE
Warmode 

### ISSUE THREAD

**Issue by Dreikaesehoe** [HateForge-WoW/Bugtracker#162]
**Beschreibe deinen Vorschlag**
Anpassung des Warmod, so wie im Konzept beschrieben. 

**Zusätzlicher Kontext**
![Screenshot 2023-12-04 181102](https://github.com/HateForge-WoW/Bugtracker/assets/151450796/4ff16f8c-8b0a-49c0-88e5-603a277bc1e2)

**Comment by Dreikaesehoe** [comment]
Oder vllt 4x Ehre am PvP Wochenende ?

**Comment by VincentADK** [comment]
Hallo, ich danke dir vielmals für deinen Vorschlag und Feedback! 
Wir haben unser Konzept angepasst und jetzt sollte es richtig dort stehen, tut uns leid!
Darüber hinaus haben wir dies auch intern besprochen und werden erst einmal nichts an dem System ändern, gleiche Begründung wie hier auch: https://github.com/HateForge-WoW/Bugtracker/issues/160
Dennoch danken wir dir vielmals und wünschen dir einen schönen Tag! :D
