### ISSUE TITLE
[Allianz] Rare-PvP-Set nicht implementiert

### ISSUE THREAD

**Issue by xkingdingelingx** [HateForge-WoW/Bugtracker#164]
**Fehlerbeschreibung**
Der Händler/NPC "Captain Dirgehammer" sollte einem die PvP-Sets verkaufen. Er hat allerdings nur das epische Set im Angebot und nicht das rare Set. Als Hauptmann sollte ich mir die Schuhe und Handschuhe kaufen können. 

Horde kann ich nicht testen, da ich dort keinen Char mit dem entsprechenden Rang habe.

**Zur Reproduktion**
Halle der Champions in SW betreten

1. Zum NPC Captain Dirgehammer gehen
2. Im Handelsfenster sollten beide Sets angeboten werden
3. Es gibt nur das epische Marschall / Feldmarschall Set

**Erwartetes Verhalten**
Der NPC verkauft laut meiner Recherche beide Sets. Mit entsprechen Ruf (aktuell Hauptmann) sollte ich mir 2 Set Teile des Rare Sets kaufen können.

**Quellenangabe**
https://www.wowhead.com/classic/de/npc=12777/captain-dirgehammer#sells;50

**Comment by schell244** [comment]
Fix kommt mit dem nächsten Update. Danke für den Report!
