### ISSUE TITLE
Ruf für Holzschundfeste - Salfa

### ISSUE THREAD

**Issue by xkingdingelingx** [HateForge-WoW/Bugtracker#165]
**Fehlerbeschreibung**
Die Quest "Aktivität der Winterfelle" von dem NPC Salfa in Winterspring ist erst ab dem Ruf "Freundlich" bei der Holzschundfeste aktiv. Laut WoW Head sollte die Quest aber nur eine Level-Restriktion haben, keine Ruf-Restriktion. Die Folge Quest "Perlen für Salfa" wird zusätzlich nicht frei geschaltet, sobald man "Aktivität der Winterfelle" abgeschlossen hat.
Soweit ich weiß sollte auf Patch 1.12 die wiederholbare Quest gar nicht mehr implemetiert sein, sondern nur die Ruf-Items (Federn/Perlen) - habe dazu aber keine verlässlichen Quellen gefunden.

**Zur Reproduktion**
NPC Salfa in Winterspring besuchen und mit ihm reden

1. Quest "Aktivität der Winterfelle" annehmen 
2. Quest "Aktivität der Winterfelle" abschließen und bei Salfa abgeben
3. Quest "Perlen für Salfa" wird nicht frei geschaltet - man hat keine möglichkeit auf die Ruf-Items.

**Erwartetes Verhalten**
Salfa sollte einem die Quest "Perlen für Salfa" geben, damit man die Ruf-Items looten kann (so wie in Felwood).

**Quellenangabe**
https://www.wowhead.com/classic/de/npc=11556/salfa
https://www.wowhead.com/classic/de/quest=8464/aktivit%C3%A4t-der-winterfelle
("Benötigt Stufe 45" ; "I started doing this at unfriendly lvl, so I dont think that rep is an issue.") 

Nachtrag: https://www.zockify.de/t/wow-classic-holzschlundfeste-guide/ (Hier sind die Voraussetzungen gut aufgelistet. Ab wann welche Quest verfügbar sein sollte)

**Comment by schell244** [comment]
Das Problem wurde mit dem letzten Update behoben. Danke für den Report!
