### ISSUE TITLE
Kriegerquest lvl50 existiert nicht

### ISSUE THREAD

**Issue by SimonMallow** [HateForge-WoW/Bugtracker#167]
**Fehlerbeschreibung**
Die Kriegerquest für lvl50 wird von keinem Kriegerleher angeboten.

**Erwartetes Verhalten**
Die Kriegerquest für lvl50 sollte in allen Hauptstädten annehmbar sein.

**Comment by schell244** [comment]
Das Problem wurde mit dem letzten Update behoben. Danke für den Report!
