### ISSUE TITLE
Mr. Smite Pathing

### ISSUE THREAD

**Issue by genever78** [HateForge-WoW/Bugtracker#17]
Habe mal einen Deadmines Besuch gemacht. Habe die beiden Adds gepullt, Smite war auf der Brücke. Smite ist dann an der Erhebung im Boden hängen geblieben, denke ich. Konnte beide Adds erledigen und nach ca. 30 Sekunden ist Smite dann weiter gelaufen.

Weiß nicht ob das an einem Timer lag oder weil beide Adds tot waren. Habe mich jedoch denke ich nicht bewegt. War ja mit Screenshot beschäftigt.

![Smite 1](https://github.com/HateForge-WoW/Bugtracker/assets/57069166/62ac7e65-5026-414f-a7d5-4515e2e7b77a)
![Smite 2](https://github.com/HateForge-WoW/Bugtracker/assets/57069166/6dbbfb79-6ade-4b30-8228-8948d4671ccb)

**Comment by Bowflinger** [comment]
Pathing/Line of sight ist im allgemeinen noch etwas verbuggt.  
z.B. die Zentaurenzelte im Brachland oder  Thousand Needles. Man kann von draußen nicht in die Zeltöffnung hereinschießen und die Mobs können teilweise das Zelt nicht verlassen und gehen auf "entkommen", bis man meele an sie heran läuft.

**Comment by Nolin7777** [comment]
Danke fuser das Ticket. Ich werde dies aber schließen und ein Allgemeines Ticket eröffnen, wo man LOS und Pathing-bugs mit coords Reporten kann, da es an einigen Stellen zu Schwierigkeiten kommt, lohnt sich ein Sammelticket.
