### ISSUE TITLE
[Druide] Umskillen / Talente verlernen in Moonglade

### ISSUE THREAD

**Issue by xkingdingelingx** [HateForge-WoW/Bugtracker#170]
**Beschreibe deinen Vorschlag**
Ich würde mich freuen, wenn der NPC "Loganaar" in Moonglade die Option zum verlernen der Talente anbieten würde.  
Dies wäre sowohl für Allie als auch Horde ein schöner QoL Change. Weder in OG, noch in IF (den meist genutzten Hauptstädten) gibt es einen Druidenlehrer. So könnte man als Druide als ersten nach Moonglade porten, umskillen und anschließend mit dem Ruhestein in die Hauptstadt.

**Zusätzlicher Kontext**
Der NPC ist als Druidenlehrer betitelt, also würde es auch Lore mäßig kein Beinbruch sein und es müsste kein NPC neu hinzugefügt werden. Ein Mondbrunnen direkt in Reichweite sorgt bestimmt auch für genug Power. ;)

**Comment by VincentADK** [comment]
Hey, vielen lieben Dank!
Wir werden das uns mal anschauen!
