### ISSUE TITLE
[PvP] Ehrenberechnung - kleiner Serverpool

### ISSUE THREAD

**Issue by xkingdingelingx** [HateForge-WoW/Bugtracker#171]
**Beschreibe deinen Vorschlag**
Durch den kleinen Serverpool ist aktuell (bzw. auch mittel- und langfristig) das ranken im PvP nur begrenzt möglich. Bei Rang 9 oder 10 ist rechnerisch Schluss.
Es wären mind. 167 Charaktere pro Woche/Abrechnung nötig, die PvP spielen - und das PRO FRAKTION - um daran etwas zu ändern. Da dies ein PvE Server ist denke ich, dass diese Voraussetzung auch mit einer größeren Community nicht erreicht wird.

Die letzten Wochen haben wir zwischen 9000-10000 Rangpunkte erhalten mit Platzierung 1. Das entspricht den RP von Bracket 4 oder 5. Durch den Decay reicht das aber ab den Höheren Rängen nicht mehr um voran zu kommen. Alle hinter Platzierung 1 bekommen dann nochmal deutlich weniger RP. 

Falls ihr gewillt seit Änderungen vorzunehmen hätte ich zwei Ansätze:

Platzierung 1 = Bracket 1 = 13.000 RP
Platzierung 2 = Bracket 2 = 12.000-12999 RP
usw.

Oder man veringert den Decay entsprechend, dass die 9000-10000 RP reichen.

Ich weiß, dass der Ehre Farm gegen die Bots hier ziemlich free ist, aber das ist halt Teil des Server Konzepts. Ranking in Classic war halt schon immer eher Zeit-Frage als alles andere. Und die Zeit muss man ja trotzdem investieren.

**Comment by Dreikaesehoe** [comment]
Das wäre eine schlechte Änderung, dann würde innerhalb kürzester Zeit jeder mit R14 gear daherkommen.
Das würde den Serverprogress massiv verzerren. Das freischalten der Epischen PvP Belohnungen sollte erst möglich sein wenn genug PvP spieler aktiv spielen.

**Comment by xkingdingelingx** [comment]
Verstehe ich, sehe ich ähnlich, aber warum nur deswegen "verbieten / nicht umsetzten"?

Hatte aufm PTR auch mal angesprochen, dass ich es bedenklich finde mit Bots, da dadurch halt 24/7 BGs laufen. Ist aber nunmal Teil des Serverkonzeptes. Und mal ganz ehrlich: Warum sollte man sich dann nicht darüber freuen vlt. grade dadurch mal die Chance zu bekommen das Gear wirklich auf einem Charakter nutzen zu können. Anstatt es nur bei anderen zu sehen.
Die Exalted-Belohnungen aus den BGs sind im Prinziep auch schon zu stark für MC - verzerrt das ganze auch. 

Und der PvE "Progress" wurde dadruch auch auf allen anderen private Servern oder den offiziellen Blizzard Classic Realms komplett zerschossen. Da war es Anfangs bei den elite Gilden wie APES oder kA wie sie alle hießen gebündelt.

Ob man jetzt gegen Bots oder richtige Spieler spielt macht am Ende der Abrechnungswoche keinen Unterschied. Man muss trotzdem mehr Spielen als alle anderen Spieler seiner Fraktion. Sogar gewinnen oder verlieren ist auf einem so kleinen Server mehr oder weniger egal. Da meist sowieso nur ein einziges BG parallel offen ist und dort alle Spieler drin sind, die ranken wollen.

Wo wir dann wieder bei dem Serverpool wären. Wie realisitsch ist das ganze mit den 167 Spielern pro Fraktion für R14? Meine Änderungen waren ja auch nur Beispiele. Man könnte ja auch an der benötigten Pool Size drehen.
Dann gebe ich dir aber schriftlich, dass sich Leute 10 Accounts erstellen und jeden Char durch 1 BG die Woche jagen. Dann könnte man es direkt anders lösen.

**Comment by Dreikaesehoe** [comment]
Dann sollen sich die Leute doch lieber 10 Accs machen und es "Abusen" anstatt es einfach so easy zumachen, du willst doch einfach nur schnell und einfach R14 gear, warum nicht gleich ein Vendor aufbauen der es für DP oder Gold anbietet ?!

Ja Bots gehören wohl zum Konzept, und die Rufbelohnungen sind stark da gebe ich auch recht. Jedoch sind die Ruf Items nicht ein Volles OP set, wenn man nach deinen Wünschen die Poolsize anpasst kann man gleich mc/bwl skippen und naxx gehen...

Doppelte Ehre im Warmode hat auch mal zum Serverkonzept dazu gehört, das hätte eher einen Positiven Effekt auf das allgemeine PVP spiel in der OpenWorld und einen mehr wert gehabt. Anstatt R14 hinterher zu schmeißen. Durch die Doppelte Ehre würde man auch nicht schneller R14, die Spieler hätten eine wichtige Entscheidung zu treffen. 

Die Poolsize Anpassung ist eine Absurde Idee.

**Comment by GTO0** [comment]
Wie würde es sich auswirken wenn man nicht die Brackets anpasst sondern die Minus RP von 20% auf 10% runter setzt, vielleicht wäre der Ansatz besser?

**Comment by Shyalya** [comment]
Diese Woche war es zB so 
1st	
[Rancypen]
	232,226 von ca. 377xx auf 40094RP
2nd	
[Dotcrit]
      230,664 von ca, 36800 auf 36444RP

Der 2 platzierte hat auf R9 sogar Rating verloren auch wenn es nicht viel war, als 2t platzierter biste angeschissen ^^
Ich hätte ein machbares Rating begrüßt. 40000RP für R14 ist auch nicht innerhalb einer woche möglich bei der geringen anzahl an PvP aktiven Menschen. 3 Wochen hat es gedauert von R9 auf R10, man könnte es ja beobachten und die RP ggf. jederzeit anpassen. 

Bezüglich Raid-Progress, nicht jeder hat Bock stundenlang PvP zu machen um sich Epics zu erfarmen, sonst würden die es jetzt auch schon machen. Die Warsong Hosen zb dürften eigtl auch erst zu AQ40 Release oder später verfügbar gewesen sein.
