### ISSUE TITLE
Sichtlinie

### ISSUE THREAD

**Issue by urkradaran** [HateForge-WoW/Bugtracker#173]
**Fehlerbeschreibung**
Feuerwerk in fässern wie bei gnomeregan oder scharlachrotes kloster lässt sich nicht aufnehmen, mit der angabe "nicht im sichtfeld"

**Erwartetes Verhalten**
klicken und dann aufnehmen...

**Screenshots**
![image](https://github.com/HateForge-WoW/Bugtracker/assets/153387749/f7349718-f413-4164-ba11-217ebd8be0c0)

**Comment by xkingdingelingx** [comment]
Sollte dieser Gegenstand sein und tatsächlich "Rote Feuerwerksrakete" enthalten, also lootbar sein.

https://www.wowhead.com/classic/de/object=103820/rote-rakete#contains;mode:normal

**Comment by schell244** [comment]
Das Problem sollte mit dem nächsten Update behoben sein. Danke für den Report!
