### ISSUE TITLE
UBRS buggt

### ISSUE THREAD

**Issue by Hordespieler** [HateForge-WoW/Bugtracker#174]
**Fehlerbeschreibung**
Die welpen in UBRS buggt.

Alle welpen die wir in UBRS geaddet haben waren nicht angreifbar

**Erwartetes Verhalten**
Sie sollten angreifbar sein

**Screenshots**
![image](https://github.com/HateForge-WoW/Bugtracker/assets/151863085/1b7f667e-7526-40c1-9748-f8e21adc9e4e)

**Zusätzlicher Kontext**
Siehe Screenshots das Rend event hat ebenfalls nicht funktioniert.

**Comment by xkingdingelingx** [comment]
Hatten wir in unserem Run am 08.12.2023 auch, als Vincent uns mit dem Rend Event geholfen hatte. 
Die Drachkin, die man aus den Eiern in den Ecken pullt sind weder Target- noch angreifbar.
Durch Reflect-DMG-Gear töten die sich zwar über Zeit selber, also Imun sind sie nicht, aber joa...

**Comment by schell244** [comment]
Fix kommt mit dem nächsten Update. Danke für den Report!
