### ISSUE TITLE
RaceChange im shop

### ISSUE THREAD

**Issue by Hordespieler** [HateForge-WoW/Bugtracker#175]
**Beschreibe deinen Vorschlag**
Hallo, ich würde gerne Vorschlagen das ihr im Shop auch einen RaceChange Token anbietet. Wenn möglich, also da man auch optisch eine andere Rasse ist. Manche haben das vielleicht nicht gewusst das man hier die Racials einfach ändern kann und sind jetzt Gnome oder so :O

Ich fände es gut wenn die Günstig wären, so dass ich die ganze Zeit meine Rasse ändern kann :D aber das ist natürlich eure Entscheidung wie ihr das implementieren wollt und ob ihr das anbieten wollt.

**Comment by GTO0** [comment]
Ich finde, dass das ein sehr gute Vorschlag ist.

**Comment by Zakryo** [comment]
Bietet auf jeden fall mehr flexibilität :)

**Comment by Dasore** [comment]
Wäre ein Träumchen

**Comment by VincentADK** [comment]
Hey danke Leute für eurer Feedback und Vorschläge!
Wir haben dies intern besprochen und werden dass im laufe des Jahres implementieren!
Danke vielmals, machts gut! :D
