### ISSUE TITLE
HC Wolf im Shop

### ISSUE THREAD

**Issue by Hordespieler** [HateForge-WoW/Bugtracker#176]
**Beschreibe deinen Vorschlag**
Moin, ich als HC spieler würde vorschlagen das es  den HC Arktischen Wolf nicht im Shop gibt... Selbst der Nicht HC Spieler der den Wolf hatte fande das nicht so gut. Bitte denkt nochmal darüber nach.

**Comment by GTO0** [comment]
Hier besagter Spieler, der es nicht gut findet. xD

**Comment by VincentADK** [comment]
Hallo, na du! Danke für deinen Vorschlag, jedoch gibt es den Wolf so nicht im Shop. Das ist ein anderes Mount. 
Hierzu kannst du gerne auch mal dir die HC Belohnungen in unserem Forum anschauen: https://forum.hateforge.de/viewtopic.php?t=27
Es gibt halt manchmal Mounts die ähnlich aussehen, jedoch nicht das gleiche sind.

**Comment by Hordespieler** [comment]
Shop Mount:

![image](https://github.com/HateForge-WoW/Bugtracker/assets/151863085/6a58ea31-e415-4006-afe2-d8c3e0b026f3)

Buff vom HC Wolf
![image](https://github.com/HateForge-WoW/Bugtracker/assets/151863085/493a33a0-bed9-4590-84e2-f28f4a3f74b1)

Cast vom HC Wolf
![image](https://github.com/HateForge-WoW/Bugtracker/assets/151863085/9eabf566-3bf0-4f9b-8228-9e54153cba3e)

Danke, für deine Antwort. Leider ist das nur die halbe Wahrheit. Faktisch alles was ein anderer Spieler sieht, selbst wenn ich streamen würde (ohne offenes Inventar mit Mouseover über dem "Wolf der Überlebenden") ist das selbe wie beim Shop Mount. 

Ich wurde sogar gefragt "warum ich mir auch das mount gekauft habe".

Wir haben das mit den noch verbliebenen HC-60ern besprochen, es geht nicht nur mir so. Es ist Super schade, denn wie man sieht ist es dann doch eine größere Herausforderung 60 mit einem HC-Char zu werden als Anfangs angenommen. 

Überdenkt bitte nochmal euren Standpunkt.

**Comment by VincentADK** [comment]
Also keine Ahnung warum du das so hinstellst als ob es Absicht ist aber okay. Das ist ein Fehler, weerde ich mal weiterleiten, danke dir!

**Comment by Hordespieler** [comment]
Hallo Vincent danke dir, es war nicht meine Absicht euch irgendwas zu unterstellen. Entschuldige bitte, wenn es so ankam.

**Comment by Nolin7777** [comment]
Hi, danke für den Report, wird morgen entfernt!
