### ISSUE TITLE
Preis Gesundheitsbrunnen

### ISSUE THREAD

**Issue by Dasore** [HateForge-WoW/Bugtracker#178]
**Beschreibe deinen Vorschlag**
Eine Quest oder zumindest eine bezahlbare Möglichkeit für den Gesundheitsbrunnen erschaffen. 5g für nen Brunnen ist für mich außerhalb einer jeden Relation. In 5er/10er geb ich ja lieber 4 bzw 9 Steine aus, als 5g zu dumpen. In Raids sind hoffentlich ein paar mehr Hexer anwesend....

**Zusätzlicher Kontext**
5g für nen Brunen... ja ne,,,,

**Comment by Nolin7777** [comment]
Wurde von 5g auf 25s runtergesetzt.
