### ISSUE TITLE
Meisterschmied Burninate hat nicht alle wiederholbaren Quests.

### ISSUE THREAD

**Issue by Brunzberth** [HateForge-WoW/Bugtracker#179]
Der NPC Meisterschmied Burninate hat nur die Quest "Restoring Fiery Flux supplies via Kingsblood"

Es sollte noch 2 andere Quests geben, für Eisenbarren und für Schweres Leder.

![WoWScrnShot_121623_092044](https://github.com/HateForge-WoW/Bugtracker/assets/153982124/5ac635d5-f9db-4156-b978-a02b84499699)

https://www.wowhead.com/classic/quest=8242/restoring-fiery-flux-supplies-via-heavy-leather
https://www.wowhead.com/classic/quest=8241/restoring-fiery-flux-supplies-via-iron
https://www.wowhead.com/classic/quest=7736/restoring-fiery-flux-supplies-via-kingsblood

Ich habe alle Quests fertig gemacht. Ich habe ohne Addons mich eingeloggt und mit einer neuen Installation es auch ausprobiert.
Das Poblem bleibt bestehen,

**Comment by Brunzberth** [comment]
![WoWScrnShot_121623_092925](https://github.com/HateForge-WoW/Bugtracker/assets/153982124/a794729e-a676-4904-8702-1660c6f18604)

Dieser Screenshot sollte aber nun funktionieren.

**Comment by schell244** [comment]
Fix kommt mit dem nächsten Update. Danke für den Report!

**Comment by schell244** [comment]
Quests sollten nun verfügbar sein.
