### ISSUE TITLE
schurkentalent

### ISSUE THREAD

**Issue by buckdie** [HateForge-WoW/Bugtracker#181]
bei dem schurkentalent unerbittliche stöße

Gewährt euren finishing moves eine chance von 20% je kombo punkt 25 energie zu bekommen.

man bekommt immer nur 25 energie beim prog.  selbst bei 5 kombo punkten

https://www.wowhead.com/classic/de/spell=14179/unerbittliche-st%C3%B6%C3%9Fe

**Comment by Texhon** [comment]
So funktioniert das Talent leider nicht.
1 Kp -> 20% Chance 25 Energie zurück zu erhalten
.
.
.
5 Kp -> 100% Chance 25 Energie zurück zu erhalten

Siehe Kommentare von 2006:
https://www.wowhead.com/classic/de/spell=14179/unerbittliche-st%C3%B6%C3%9Fe#english-comments

**Comment by VincentADK** [comment]
Hey vielen lieben Dank euch beiden!
Ja, es ist genauso, wie Texhon sagt, ist ein wenig irreführend geschrieben im Fähigkeitstext, aber genau so funktioniert es. 
Falls noch ein Problem bestehen sollte ruhig hier wieder drunter schreiben und dann werde ich das Problem wieder öffnen! 
Machts gut und habt einen schönen Tag!
