### ISSUE TITLE
ehrenabzeichen aus schlachtfelder

### ISSUE THREAD

**Issue by buckdie** [HateForge-WoW/Bugtracker#182]
normal sollte man bis 100 marken bekommen können bevor sie per post geschickt werden.
hier kann man 20 in besitz haben.  rest kommt per mail

**Comment by Texhon** [comment]
Es war laut alter Kommentare bei Wowhead erst später möglich bis zu 100 Marken im Inventar zu haben. Zuvor waren es 20er Stacks und später 30er. Die übrigen Marken verbleiben leider nur 24 Stunden im Briefkasten. 
https://www.wowhead.com/classic/item=20558/warsong-gulch-mark-of-honor#comments
https://www.wowhead.com/classic/item=20559/arathi-basin-mark-of-honor#comments

**Comment by VincentADK** [comment]
Wie Texhon sagt; ist das ganz Normal, ist also Blizzlike. Daran werden wir nichts ändern, nach Absprache im Team. Dennoch danken wir dir vielmals für deinen Vorschlag!
