### ISSUE TITLE
Non-HC Levelrestriktion

### ISSUE THREAD

**Issue by Dreikaesehoe** [HateForge-WoW/Bugtracker#183]
![image](https://github.com/HateForge-WoW/Bugtracker/assets/151450796/58ffb8b7-f1e1-4fc2-b2e3-64033922f162)

**Comment by Dreikaesehoe** [comment]
Der Handel ist davon auch betroffen

**Comment by schell244** [comment]
Fix kommt mit dem nächsten Update. Danke für Melden!
