### ISSUE TITLE
NPC in Sonnenfels ohne Textur

### ISSUE THREAD

**Issue by nn-23** [HateForge-WoW/Bugtracker#184]
Winterfeiernder in Sonnenfels fehlen Texturen:

![grafik](https://github.com/HateForge-WoW/Bugtracker/assets/21192997/a780259d-0eed-4bb1-82ef-e1896ad99a0b)

**Comment by VincentADK** [comment]
Hey, danke dir für deinen Beitrag!
Bei mir funktioniert alles, bitte schaue mal ob du einen WDB Ordner hast und wenn ja lösche diesen bitte einmal und starte den Klienten wieder. Sollte damit behoben sein, sprich kein Bug sein. Falls dies jedoch dann imemr noch sein sollte, lass es uns bitte wissen!
