### ISSUE TITLE
50er Schamanen Klassenquest

### ISSUE THREAD

**Issue by Zakryo** [HateForge-WoW/Bugtracker#186]
Hey Hateforge Team, 

leider kann ich die 50er Schamanen Klassenquest nicht annehmen da die Quest nicht beim Klassenlehrer verfügbar ist. Weder in TB noch in OG. Die Quest heißt "Elementarbeherrschung" und schickt einen eigentlich ins Vorgebirge, von wo aus es in den Tempel mit der Quest "Da Voodoo" geht. Ich hoffe ihr könnt mir helfen. 

Grüße Moonset

**Comment by VincentADK** [comment]
Scheint wohl ein Problem mit dem Patch System zu sein, ich konnte ihm die Quest leider nicht geben. Also kann damit Bestätigen das es ein Problem gibt. :D

**Comment by schell244** [comment]
Fix kommt mit dem nächsten Update. Danke für den Report!
