### ISSUE TITLE
Vorschlag Shop Umskillitem

### ISSUE THREAD

**Issue by Hordespieler** [HateForge-WoW/Bugtracker#187]
Moin, wir sitzen hier zusammen und fänden alle ein Item klasse, das man gerne auch über den Shop, dazu benutzen kann um Mobil umskillen zu können, wäre sowas möglich? :D

**Comment by Dasore** [comment]
So ein Teil wäre ein Träumchen. Kennt man ja auch von anderen Servern!

**Comment by Nolin7777** [comment]
Gibt's beim Reagenzienhaendler um 1g.
