### ISSUE TITLE
Schwerere Mob Wellen in UBRS (Rend Arena Event)

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#19]
**Beschreibe deinen Vorschlag**
Dies kommt von Simon vom Discord!
Er wünscht sich schwerere Mob Wellen bei dem UBRS Arena Event!
Also das man da nicht komplett durchmäht!
Die Pausen waren ihm einfach zu lang (auf Turtle WoW als Beispiel).
Vielleicht könnte man diese etwas schwerer machen so wenn man eine Trinkpause macht das man so auf 75% Mana kommen könnte (Zeitspanne). 
So in etwa meint er! :D

**Zusätzlicher Kontext**
-

**Comment by Nolin7777** [comment]
Gerne!

**Comment by SimonMallow** [comment]
Wir haben gestern das Event in UBRS nun testen können und mit einer 9er Gruppe mit Pre Raid Bis Gear und dieser 5% Reg Nahrung aus der Box. Unter diesen Umständen haben einige Spieler gesagt, dass sie mit dem Reggen gerade so fertig wurden. Der Schaden hat bei allen bis auf einer Welle insofern ausgereicht, als dass wir die Gruppen down hatten bevor die nächste Welle auftrat.

Mein Fazit dazu ist also, dass ich denke, dass bei deinem 45 Sekunden-Timer bei einer 10er Gruppe mit normalem Gearstand zu beginn ordentlich Ackern werden. Es wird sich zeigen wie gut das läuft aber ich schaue positiv auf die ersten Runs unter realen Umständen. :)

**Comment by JackoRackham** [comment]
Ich kann hier @SimonMallow nur zustimmen.
Eine Anmerkung hierzu: Hätte hier ein Spieler gerezzt werden müssen, wäre es sich mit dem Timer / Manareggen nicht ausgegangen.

**Comment by Nolin7777** [comment]
Die Wellen wurden verkürzt!
