### ISSUE TITLE
Schärpe mit Monogramm Quest kann man bei Kapitän Hecklebury Smotts nicht abgeben

### ISSUE THREAD

**Issue by Umkaluabo** [HateForge-WoW/Bugtracker#194]
Wenn man in Stranglethorn den Mob Mok'rash umhaut droppt dieser Schärpe mit Monogramm.
https://datenbank.classic-wow.de/?item=3985

Wenn man die Quest annimmt, sollte man diese bei Kapitän Hecklebury Smotts abgeben können.
https://datenbank.classic-wow.de/?npc=2500

Dieser hat aber kein Symbol zum abgeben der Quest.

**Comment by VincentADK** [comment]
Hey, danke dir für deinen Bugreport! Hier ist bereits schon ein Ticket dafür offen: https://github.com/HateForge-WoW/Bugtracker/issues/157
Ich werde das hier mal schließen. Machs gut!
