### ISSUE TITLE
Game crash Felwood quests

### ISSUE THREAD

**Issue by Dotcrit** [HateForge-WoW/Bugtracker#196]
When taking BOTH quests from Grazle in Felwood called [Timbermaw Ally] (yes they have the same name + objective) the game causes instant crashes. Individual taking the quests is all good but when taking both quests instant crashes cause, only to be solved by a GM removing the quests.

Kind regards,

Dotcrit

**Comment by VincentADK** [comment]
Here are both quests:
https://www.wowhead.com/classic/quest=8460/timbermaw-ally
https://www.wowhead.com/classic/quest=6131/timbermaw-ally
Had to remove both quests from him so he could log back in again and play normaly. 

Here is the NPC Info: 
![gibt immernoch dieses Problem 2](https://github.com/HateForge-WoW/Bugtracker/assets/125162204/94e3ecf4-38b4-48c3-acb6-917e44415b95)

**Comment by VincentADK** [comment]
This was with the english 1.12.1 client (enUS)

**Comment by VincentADK** [comment]
We are currently working on this, this was the problem: https://www.wowhead.com/classic/quest=6131/timbermaw-ally
This quests shouldn't be there.

**Comment by schell244** [comment]
Das Problem sollte bereits behoben sein. Danke dür den Report!
