### ISSUE TITLE
Geänderte Bot anzahl im Arathibecken.

### ISSUE THREAD

**Issue by GTO0** [HateForge-WoW/Bugtracker#197]
**Fehlerbeschreibung**
Die Bot Anzahl im Arathibecken wurde wohl von 10 auf 14 hochgesetzt was dazu führt, dass sobald ein Spieler im BG ist kein zweiter Joinen kann auch wird kein neues BG eröffnet wenn man sich anmeldet was dazu führt, dass aktuell jeweils nur ein Spieler ins Arathibecken kann.

**Comment by VincentADK** [comment]
Das sollte jetzt wieder gut sein oder? Wir haben die Anzahl an Bots für AB wieder abgeändert. Kannst du das zufällig bestätigen?

**Comment by xkingdingelingx** [comment]
Geht wieder, ja.

**Comment by VincentADK** [comment]
Super, vielen lieben Dank! <3
