### ISSUE TITLE
Eine kleine Liste an Sachen die man testen könnte von Simon!

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#20]
**Beschreibe deinen Vorschlag**

- die Kanone und das Tor und die Wachen am Tor in den Deadmines.
- das Spawnen und laufen von Patchwork im Duskwood
- die Truhe in der Arena von Gurubashi
- die Statuen für den Bosskampf im Versunkenen Tempel
- der Endbosskampf im Versunkenen Tempel
- die Schlüsselquest für UBRS - da war die Droprate einzelner Kristalle auf TurtleWoW so schlimm, dass viele die Quest nicht gemacht                    haben
- das Arenaevent in UBRS, LBRS und BRD - btw. ich meine das Arenaevent in UBRS ist immer langweilig generell sollte die Pausenphase                           - deutlich verkürzt werden, würde mich da auch als Tester anbieten
- der Spawn der Bestie in UBRS
- das Kneipenevent in BRD (weiß den Namen vom Golem nicht) funktioniert das richtig?)
- das Treppenevent in ZulFarak
- der Goblin in ZulFarak, welcher das Tor anschließend sprengen soll
- das Gongevent für Grazilla in ZulFarak
- das Bibiliotheksevent in Scholomance
- das Spawnen des Gargoyle-Bosses in Scholomance (samt Blut, Tor verschließen etc.)
- in Stratholme der Kampf auf dem Platz in StrahUD gegen die Bestien - (schließt das Tor, öffnet sich anschließend der Zigurrat, kommen die Bestien automatisch etc.?)
- die Postkastenquest in Stratholme
der Enbosskampf in Burg Schattenfang (portet der Boss richtig?)
- Funktioniert die Onyxiaquestreihe inkl. der Escortquest in LBRS? Ist wirklich wichtig, das würde die Leute schwer abfucken, wenn nicht
Reagieren die Wachen von der Steamwheedle-Fraktion alle richtig?

**Zusätzlicher Kontext**
-

**Comment by Bowflinger** [comment]
Ich würde "Drain Life/Blutsauger" und "Siphon Life/ Lebensentzug" noch auf die Testliste setzen.
Auf vielen Privatservern werden diese Zauber fälschlicherweise von MS Effekten beeinflusst. Wie man an [hier](https://wowpedia.fandom.com/wiki/Patch_2.3.0) (strg+f "warlock" ) sehen kann, kam das aber erst mit Patch 2.3.

Den Hexer zum testen hätte ich sogar (ktcwarlock), aber da ich kein Ork bin,  brauche ich einen Krieger/Schurken zum testen.

**Comment by genever78** [comment]
Kanone in DM geht.
Gurubashi habe ich ca 10 Trinkets gelootet.

**Comment by Nolin7777** [comment]
Danke, die Liste behalten wir intern für Testzwecke.

**Comment by Bowflinger** [comment]
BRD Kneipe: 

- Wenn man den Zwerg besoffen macht (was nach 5 mal Bier abgeben geklappt hatte) öffnet der Golem die Tür und wird feindlich
- Man kann den Schlüssel vom Barkeeper-Gnom per Taschendiebstahl klauen
- Succubus Quest habe ich noch nicht getestet

_____
Ubrs- Schlüssel / LBRS:

- random drop, der die Quest startet, droppt
- NPC verlässt seine Tarnung und startet die Quest (für alle Spieler - ich weiß nicht, ob es eigentlich nur die Person mit dem item sein sollte)
- nach ca. 7 runs haben wir die Kristalla von Omokk und Voone jeweils einmal bekommeb, was zu den ~20% dropchance (laut atlas loot) passen sollte. Bei der geringen Anzahl an runs, kann es beim Enboss Pech gewesen sein (oder am verbuggten loot table liegen, siehe offenes [Ticket](https://github.com/HateForge-WoW/Bugtracker/issues/35))

______
Strath UD:

- Ziggurate öffnen sich nach dem Boss-Kill
- Der Magister, der den Schlüssel droppt, rennt korrekterweise nur weg, wenn man durch die Hintertür reingeht
- Das Fleischklops Event auf dem Vorplatz funktioniert
