### ISSUE TITLE
Gold will nicht bei mir bleiben

### ISSUE THREAD

**Issue by Laira333** [HateForge-WoW/Bugtracker#200]
**Fehlerbeschreibung**
Eine klare und präzise Beschreibung des Fehlers.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Gehe zu '...'
2. Klicke auf '....'
3. Siehe Fehler

**Erwartetes Verhalten**
Eine klare und präzise Beschreibung dessen, wie es zu funktionieren hat.

**Screenshots**
Füge gegebenenfalls Screenshots hinzu, um das Problem zu verdeutlichen.

**Quellenangabe**
Um das Problem lösen zu können, müssen wir die Richtigkeit des "Erwartetes Verhalten" anhand von offiziellen Quellen prüfen. Füge einen Link zu einer offiziellen Quelle hinzu.

**Zusätzlicher Kontext**
Falls vorhanden, füge hier weitere Informationen zum Problem hinzu.

**Comment by VincentADK** [comment]
Ein bisschen mehr Informationen hierzu wäre toll.

**Comment by Laira333** [comment]
Als ich mich eingeloggt habe hatte ich 163G bin dann nach Southshore geflogen um zum Av anmelder gegangen vor der Höhle hatte ich die Q für die Stangenwaffe wo man (korrot?) killen muss.
Hab dann ein AV gemacht und danach bin ich nach IF geflogen um die waffe zu skillen ... hab dann iwann gemerkt das mir 150G fehlen und ich war NICHT im AH, Händler  ODER habe mit einem anderen spieler getradet.

**Comment by VincentADK** [comment]
Hat sich zum Glück erledigt, die Epische Pferdchen Quest war der Übeltäter!
