### ISSUE TITLE
Creeper Ichor dropchance erhöhen

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#204]
**Beschreibe deinen Vorschlag**
Die Dropchance von dem Creeper Ichor bei der Quest: "Elixir of Suffering" erhöhen, da diese sehr gering ist (ist Normal, aber sehr Nervig).
(Ticket im Spiel diesbezüglich bekommen.)

**Zusätzlicher Kontext**
https://www.wowhead.com/classic/quest=496/elixir-of-suffering#comments
https://www.wowhead.com/classic/item=3477/creeper-ichor

**Comment by schell244** [comment]
Wurde angepasst und kommt mit dem nächsten Update. Danke dir!
