### ISSUE TITLE
Gasthaus Feathermoon Runenstein

### ISSUE THREAD

**Issue by Dasore** [HateForge-WoW/Bugtracker#205]
Wenn man vor der Tresen der Gastwirtin (Shyria) steht und mit ihr spricht, kann man auswählen diesen Ort für den Runenstein zu wählen. Es passiert aber nichts. Erst wenn man auf die Tresen springt, dann kann man ihn setzten. 
Wenn man davor steht, macht sie zwar ihre Animation, aber die blaue Animation am Spielercharakter fehlt.

**Comment by schell244** [comment]
Fix kommt mit dem nächsten Update. Danke für den Report!
