### ISSUE TITLE
Duelle gegen Gruppenmitglieder nicht möglich

### ISSUE THREAD

**Issue by Bowflinger** [HateForge-WoW/Bugtracker#21]
**Fehlerbeschreibung**
Wenn man ein Duell gegen Gruppenmitglieder startet, werden sie zwar rot/feindlich angezeigt, aber man die Fehlermeldung "ungültiges Ziel".
Wenn man nicht in einer Gruppe ist, funktioniert es ohne Probleme.
Getestet haben wir es auf 2 Hordencharakteren.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Gruppe bilden
2. Duell starten

**Erwartetes Verhalten**
Man kann sich gegenseitig angreifen.

**Comment by schell244** [comment]
Fixed. Danke für den Report!
