### ISSUE TITLE
Der Loot der Prinzessin Moria Bronzebard wird nicht korrekt verteilt.

### ISSUE THREAD

**Issue by haferjir** [HateForge-WoW/Bugtracker#211]
**Fehlerbeschreibung**
Die Items der Prinzessin aus BRD werden teilweise nicht verrollt, sondern ich gewinne diese automatisch. Sie erscheinen auch nicht im Loot-Log der anderen Spieler:innen

**Zur Reproduktion**
Mache einen BRD-Run mit Dogir.
Töte die Prinzessin
Dogir gewinnt das Item der Prinzessin automatisch.
Andere Leute im Chat konnten das Problem nich bestätigen, aber mit Dogir haben wir es an mehreren Tagen unabhängig von der genauen Gruppen-Zusammenstellung gesehen.

**Erwartetes Verhalten**
Das Item wird wie alle anderen verrollt.

**Screenshots**
![image](https://github.com/HateForge-WoW/Bugtracker/assets/2912298/cdaed229-2ebc-4124-b9a8-305d78b5eb4c)

**Quellenangabe**
Does not apply.

**Zusätzlicher Kontext**
Beim ersten mal hatte uns Vincent geholfen und das Item umgeschoben.

**Comment by xkingdingelingx** [comment]
Checkt bitte mal alle, ob ihr die "Pre Quest" gemacht habt, bevor nach einem Fehler gesucht wird. Man benötigt eine Quest, um den Loot der Prinzessin überhaupt sehen/drum rollen zu können.

**Comment by haferjir** [comment]
Fazinierend, danke für die Einordnung.

**Comment by VincentADK** [comment]
https://www.wowhead.com/classic/quest=4363/the-princesss-surprise
