### ISSUE TITLE
Rogue Class Quest Horde: No Touch of Zanzil.

### ISSUE THREAD

**Issue by lukzak** [HateForge-WoW/Bugtracker#212]
During the Horde Rogue level 20 class quest, you should get the debuff "Touch of Zanzil", which is the purpose of traveling to Tarren Mill to get the poison cured (and learn how to use make poisons for our own weapons).

After looting the Cache of Zanzil's Altered Mixture for the quest Mission: Possible But not Probable(2478), the poison should be applied. Right now, it is not applied. It is evident in the quest text that we should be infected with the poison, but it is not applied upon unlocking the box for the quest.

Additionally, upon completing the quest chain, we are rewarded with the antidote to the poison that we are NOT infected with.

**Comment by xkingdingelingx** [comment]
Poison was applied on PTR when i tested it. But the Poison had no effect at all.

https://github.com/HateForge-WoW/Bugtracker/issues/40

Maybe they tried fixing the issue and created a new one ;-P

**Comment by schell244** [comment]
Touch of Zanzil will be applied again after next update. The effect remains to be fixed. Thanks for the Report!
