### ISSUE TITLE
Questmob Deathclasp / Totenstachel fehlt (Silithus)

### ISSUE THREAD

**Issue by nn-23** [HateForge-WoW/Bugtracker#213]
Habe die Q Gesucht: Totenstachel, Terror der Wüste in Silithus angenommen, der Mob ist aber nicht da.
Auch in der Datenbank finde ich den nicht. Das Q Item schon, aber nicht den Mob.

https://hateforge.de/en/item/20385
https://www.wowhead.com/classic/npc=15196/deathclasp
https://www.wowhead.com/classic/quest=8283/wanted-deathclasp-terror-of-the-sands

**Comment by schell244** [comment]
Fix kommt mit dem nächsten Update. Danke für den Report!
