### ISSUE TITLE
Auctionhaus scannen mit Auctioneer seit den AH Bots

### ISSUE THREAD

**Issue by Luamara91** [HateForge-WoW/Bugtracker#216]
**Fehlerbeschreibung**
Das AH mit Auctioneer scannen dauert deutlich länger. Jede Seite wird mindestens einmal neu gescant, weil es pro Seite länger als 20 Sekunden dauert. Man muss auch am PC sein weil sonst der Charakter AFK geht und das AH schließt. Einmal das AH scannen hat ca. 10 Minuten gedauert.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Installiere Auctioneer
https://legacy-wow.com/vanilla-addons/Auctioneer/  
https://legacy-wow.com/vanilla-addons/enchantrix/
https://legacy-wow.com/vanilla-addons/EnhTooltip/
https://legacy-wow.com/vanilla-addons/Stubby/
2. Gehe zum Auktionshaus
3. Drücke auf Scan

**Erwartetes Verhalten**
Das AH wird in 1-2 Minuten gescannt. Ohne Meldung im Chat das Seiten neu gescannt werden müssen. 

**Screenshots**
![WoWScrnShot_011724_125540](https://github.com/HateForge-WoW/Bugtracker/assets/156676417/20a7d546-0a2c-494e-ac72-51c79f24f5f3)

![WoWScrnShot_011724_130923](https://github.com/HateForge-WoW/Bugtracker/assets/156676417/1cb8fc11-c920-4364-bb7b-2fd9a2fe8ad8)

**Zusätzlicher Kontext**

Edit: Ich vermute Auctioneer kommt nicht damit klar, das Items ohne Verkäufernamen im AH sind, oder ihr habt das Ah so geändert für den Bot, dass Auctioneer nicht damit klar kommt. Woina hat mir gesagt das addon aux geht bei ihm.

Zitat: Spielerinteraktion: Der Bot greift nicht in Spieler-zu-Spieler-Transaktionen ein. @everyone's  Geschäfte bleiben unberührt und weiterhin im Mittelpunkt!

Ich werde nicht am PC sitzten um das AH zu scannen, nur um sicher zu stellen man Bankchar ist nicht AFK geht. Ich habe auch kein Platz für die ganzen Items, also wenn das so bleibt ziehe ich mich als Verkäufer aus dem AH komplett zurück und verkaufe Sachen die ich oder meine Gilde nicht benötigt einfach beim NPC.

**Comment by VincentADK** [comment]
Hallo Luamara!
Wir bedanken uns ganz herlichst bei dir für deinen Bericht, jedoch müssen wir diesen ablehnen. 
Wir sind nicht dafür verantwortlich ob ein Addon funktioniert oder nicht, wir können und werden dies auch nicht angehen. 
Sprich wir werden nicht Addons bearbeiten die nicht von uns selber kommen. 
Manche Addons machen halt manchmal Probleme. Was du versuchen könntest wäre mal das Addon zu deaktivieren und dieses wieder zu aktivieren. Manchmal hilft es auch eine Neuinstallation des Addons vorzunehmen. 
Wir wünschen dir dennoch einen schönen Tag und mach es gut!
