### ISSUE TITLE
Deathclap does not drop it's quest items

### ISSUE THREAD

**Issue by Dotcrit** [HateForge-WoW/Bugtracker#217]
I recently took the quest of Deathclasp in Silithus, however he did not drop his quest item
It's this quest: https://www.wowhead.com/classic/quest=8283/wanted-deathclasp-terror-of-the-sands
It should drop this item: https://www.wowhead.com/classic/item=20385/deathclasps-pincer
Heres my screenshot:
![Uploading Screenshot_15.png…]()

Kind regards,

Dotcrit

**Comment by Dotcrit** [comment]
![Screenshot_15](https://github.com/HateForge-WoW/Bugtracker/assets/154899754/dfe0c49f-40d1-4068-8669-a672451792f4)

**Comment by Dotcrit** [comment]
+ combat log when you're in doubt ^^ 
![Screenshot_16](https://github.com/HateForge-WoW/Bugtracker/assets/154899754/419a526b-708b-4520-a598-c4ded78643d6)

**Comment by schell244** [comment]
Will be fixed with next update. Thanks for the report!
