### ISSUE TITLE
Einige Ideen für Anpassungen vom AH-Bot:

### ISSUE THREAD

**Issue by Dasore** [HateForge-WoW/Bugtracker#223]
- Materialien in random anderen Stackgrößen wie 1 anbieten
- Rüstung / Waffen reicht auch mal eines pro Level, nicht 10x das gleiche Grunditem mit verschiedenen Endungen
- 95% der Rezepte entfernen... (Wer braucht die ganzen Kochrezepte und dann auch noch in der Gleichheit?)
- Rüstung / Waffen unter Level 10 braucht kein Mesch

Aktuell ist jetzt das AH zwar schön voll, nur 95% davon könnte auch raus weils keiner jemals braucht....

Ebenfalls sollten auch die AH Gebühren niedrig gehalten werden.

**Comment by Hordespieler** [comment]
Leider muss ich Dasore zustimmen. Das AH wird vom Bot gefüllt und von spielern ignoriert. Es ist tot. Richtig, richtig Tot. Ein Spieler zahlt nur drauf wenn er dinge anbietet. Es macht keinen Sinn.

**Comment by Dasore** [comment]
AH Zeit von Items wieder verdoppeln
Einstellgebühren auf 1/4 - 1/5

**Comment by Nolin7777** [comment]
Danke fuer die Vorschläge, kommt mit dem nächsten Update.
