### ISSUE TITLE
Princess Moira Bronzebeard <Princess of Ironforge> hat keinen Loot

### ISSUE THREAD

**Issue by Umkaluabo** [HateForge-WoW/Bugtracker#228]
Die Princess Moira Bronzebeard <Princess of Ironforge> in der BRD droppt keinen Loot.

Normalerweise sollte dieser Loottable drin sein:
https://www.wowhead.com/classic/npc=8929/princess-moira-bronzebeard

**Comment by VincentADK** [comment]
Hast du die passende Quest vorher gemacht? Dieses Problem wurde schon öfters gemeldet, schau mal bitte hier: 
https://github.com/HateForge-WoW/Bugtracker/issues/211

**Comment by VincentADK** [comment]
Hier wäre die letzte Quest die man machen mus: https://www.wowhead.com/classic/quest=4363/the-princesss-surprise
Ist also kein Bug, ich zitiere: 

"The Princess's Surprise is a dungeon quest that is begun by finding and speaking with [Kharan Mighthammer](https://www.wowhead.com/classic/npc=9021/kharan-mighthammer), who is imprisoned in the Detention Block of [Blackrock Depths](https://www.wowhead.com/classic/zone=1584/blackrock-depths). After players speak with Kharan, they must clear their way to the end of the dungeon and slay [Emperor Dagran Thaurissan](https://www.wowhead.com/classic/npc=9019/emperor-dagran-thaurissan) without killing [Princess Moira Bronzebeard](https://www.wowhead.com/classic/npc=8929/princess-moira-bronzebeard). Once the emperor is slain, Moira will become friendly and offer the quest The Princess's Surprise. Completing The Princess's Surprise awards players with either[ Magni's Will](https://www.wowhead.com/classic/item=12548/magnis-will), a ring great for feral druid tanks and dps, hunters, retribution paladins, rogues, and warrior dps and tanks, or[ Songstone of Ironforge](https://www.wowhead.com/classic/item=12543/songstone-of-ironforge), a good ring for Balance Druids, Mages, Healing and Shadow Priests, and warlocks. Additionally, completing The Princess's Surprise also allows players access to Moira's loot table in future [Blackrock Depths](https://www.wowhead.com/classic/zone=1584/blackrock-depths) runs."

**Comment by Umkaluabo** [comment]
Ok, ich habs grad nachgelesen, auf anderen Servern ist mir das nie aufgefallen, dass man zuerst die Quest machen muss für den Loot. Dann kanns geschlossen werden, ich hab die aktuelle Quest noch im Log.
