### ISSUE TITLE
/who zeigt zu viele Leute an

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#23]
**Fehlerbeschreibung**
Auf unserer Webseite steht das wir 7 Spieler online haben und im Spiel sieht man im /who Fenster das wirklich 7 Leute online sind. Jedoch zeigt die Zahl zu viele Spieler an, die gar nicht da sind. Sind das vielleicht alle gemachten Charaktere? Oder weil gerade Leute im BG sind mit den PvP Bots?

**Zur Reproduktion**
Gehe auf unsere Webseite, schaue wie viele Leute online sind, dann schaue im Spiel via /who wie viele Spieler da sind und vergleiche bitte! Vielleicht auch mal ins BG gehen und schauen ob es an den PvP Bots liegt!

**Erwartetes Verhalten**
Sollte genauer anzeigen wie viele Leute online sind (/who)!

**Screenshots**
https://imgur.com/a/gbhsTkq

**Quellenangabe**
-

**Zusätzlicher Kontext**
-

**Comment by schell244** [comment]
Fixed, Danke :)
