### ISSUE TITLE
Ergänzung eines Talentplaners auf der Webseite

### ISSUE THREAD

**Issue by JackoRackham** [HateForge-WoW/Bugtracker#24]
Für die Webseite wäre ein Talentplaner (evtl. mit angepassten Tooltips, falls Talente geändert werden/wurden) wünschenswert.

**Comment by Nolin7777** [comment]
Gerne!

**Comment by JackoRackham** [comment]
Hier ein Beispiel:
https://github.com/maladr0it/classic-talent-calculator

**Comment by Nolin7777** [comment]
https://talents.hateforge.de/

**Comment by YamaYAML** [comment]
Framed within the general lay-out with be nice-to-have. E.g. https://legacyplayers.com/tools/talents but then following the mentioned page. Something for the backlog. :)
