### ISSUE TITLE
Items des i58 Boosts für Chars >= 58 verfügbar machen

### ISSUE THREAD

**Issue by JackoRackham** [HateForge-WoW/Bugtracker#244]
Um Spieler, die ohne Boost auf Level 58 oder weiter gelevelt haben nicht zu benachteiligen, sollten Diese die Möglichkeit haben, die Items aus dem Boost z.B. von dem NPC einmalig zu erhalten.

**Comment by Nolin7777** [comment]
Kommt mit naechsten Update!
