### ISSUE TITLE
WoW.exe mit dem LAA Flag versehen

### ISSUE THREAD

**Issue by JackoRackham** [HateForge-WoW/Bugtracker#25]
Die WoW.exe hat das Large Address Aware flag nicht gesetzt, da die heutigen Systeme zumeist deutlich mehr als 2 GB haben sollte die Exe in den Downloads vielleicht mit dem Flag versehen werden, so das die Anwendung bis zu 4 GB Speicher nutzen kann.

**Comment by Nolin7777** [comment]
Der Download steht im User Panel zur Verfügung.
