### ISSUE TITLE
"Cannonball Runner" aus Bot Gear entfernen

### ISSUE THREAD

**Issue by sep-san** [HateForge-WoW/Bugtracker#253]
**Beschreibe deinen Vorschlag**
Bitte entfernt das Trinket "[Cannonball Runner](https://www.wowhead.com/classic/item=13382/cannonball-runner)" aus dem Bot Gear. Dieses pullt gerne adds.

**Zusätzlicher Kontext**
Danke :-)

**Comment by Nolin7777** [comment]
Danke, wird beim naechsten restart behoben
