### ISSUE TITLE
HC Mount "Wolf of Survivors" nur noch 60%

### ISSUE THREAD

**Issue by Cyri-GitHub** [HateForge-WoW/Bugtracker#255]
**Fehlerbeschreibung**
Der Wolf welcher als HC Belohnung 100% Mount Speed geben sollte gibt nur noch 60%

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Mount benutzen

**Erwartetes Verhalten**
100% mountspeed 

**Screenshots**
-

**Quellenangabe**
-

**Zusätzlicher Kontext**
Vielleicht kann ja bei dieser Gelegenheit auch das andere Mount "Stallion of Survivors" angepasst/gefixt werden. (Siehe Issue #210)

**Comment by Nolin7777** [comment]
Danke, wird behoben beim naechsten restart!
