### ISSUE TITLE
Zul gurub flex

### ISSUE THREAD

**Issue by urkradaran** [HateForge-WoW/Bugtracker#259]
**Fehlerbeschreibung**
Bosse hatte gleich viele leben (gemäss addon von mitspielern) wie bei 20 leuten, waren aber mit 11 drin

**Zur Reproduktion**
Spieler/bots in ZG hinstellen und beobachten ob sich max leben verändern bei den bossen

**Erwartetes Verhalten**
Leben passen sich der anzahl spieler an von 12-20

**Screenshots**
-

**Quellenangabe**
Gemäss wowhead und ingame addons lebenspunkte verglichen.

**Zusätzlicher Kontext**
-

**Comment by Nolin7777** [comment]
Wurde gefixt, danke
