### ISSUE TITLE
Nachtelfen corpse run

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#26]
**Beschreibe deinen Vorschlag**
Simon fragte ob wir vor haben daran etwas zu ändern. 

Meine Ideen: Vielleicht ein Portal im Tempel der Elune das man benutzen kann.
Oder einen NPC Magier der einen nach Ironforge porten würde, gegen etwas Taschengeld versteht sich natürlich.

**Zusätzlicher Kontext**
-

**Comment by Nolin7777** [comment]
Abgelehnt.
