### ISSUE TITLE
SoR Schaden über Tod führt zur Meldung "Ungültiges Ziel"

### ISSUE THREAD

**Issue by JackoRackham** [HateForge-WoW/Bugtracker#27]
**Fehlerbeschreibung**
Wenn ein Mob durch den White Hit stirbt bei aktivem SoR führt der Seal Schaden zu einer Meldung ungültiges Ziel

**Zur Reproduktion**

1. SoR aktivieren
2. Gegner angreifen
3. Wenn der Gegner durch den Melee Schaden (White hit) stirbt kommt die Meldung ungültiges Ziel

**Erwartetes Verhalten**
Der Proc sollte nicht mehr kommen, da das Ziel bereits tot ist, somit sollte auch keine Meldung kommen.

**Screenshots**
![Combatlog_SoR_InvalidTarget](https://github.com/HateForge-WoW/Bugtracker/assets/120782983/f2bf1d38-acd6-4013-811e-2936e224dd80)

**Comment by VincentADK** [comment]
Hallo!
Vielen lieben Dank für dein Report!
Das Problem sollte jetzt behoben sein: https://streamable.com/12npuc
