### ISSUE TITLE
Angreifbare Argentumdämmerung ohne im Krieg zu sein

### ISSUE THREAD

**Issue by SimonMallow** [HateForge-WoW/Bugtracker#28]
**Fehlerbeschreibung**
Ich kann gegen die NPCs der Argentumdämmerung kämpfen, obwohl ich nicht im Krieg mit dieser Fraktion stehe.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren: Man kann die NPCs direkt angreifen.

1. Gehe zu 'Chillwind Outpost'
2. Klicke auf 'einen beliebigen Argentumdämmerungsoffizier'
3. Siehe Fehler

**Erwartetes Verhalten**
Ich erwarte, dass ich freundlich mit den NPCs bin und diese nicht attakieren kann.

**Screenshots**
Füge gegebenenfalls Screenshots hinzu, um das Problem zu verdeutlichen.
![NPCsAngreifbar](https://github.com/HateForge-WoW/Bugtracker/assets/143521488/3ee25dd1-796e-48f7-a049-0a838a563333)

**Quellenangabe**
Um das Problem lösen zu können, müssen wir die Richtigkeit des "Erwartetes Verhalten" anhand von offiziellen Quellen prüfen. Füge einen Link zu einer offiziellen Quelle hinzu.

**Zusätzlicher Kontext**
Falls vorhanden, füge hier weitere Informationen zum Problem hinzu.

**Comment by Nolin7777** [comment]
... weil du den Ashbringer equippt hast.

**Comment by SimonMallow** [comment]
Good to know!
