### ISSUE TITLE
Die EXP Trinket Quests "gehen" nicht mehr

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#30]
**Fehlerbeschreibung**
Man kann die EXP Trinket Quests nicht mehr annehmen. Der Questgeber gibt gar keine Quests mehr, selbst wenn man diese nocht nie abgeschlossen hatte!

**Zur Reproduktion**
Gehe nach Orgrimmar oder Stormwind zu den Portallehren und versuche die Quests für die Trinkets zu bekommen.

**Erwartetes Verhalten**
Normalerweise sollte der NPC die Quests dir ab level 10 geben.

**Screenshots**
https://streamable.com/c2ixgu
https://streamable.com/igg5nv

**Zusätzlicher Kontext**
Laut Ktc von unserem Discord, ist dieser Fehler aufgetretten, nachdem Neustart wo dann The Box NPCs wieder implementiert wurden sind.

**Comment by schell244** [comment]
Fixed, Danke! :)

**Comment by Ropp7** [comment]
**Beschreibung:**
Lt. dem Patch 0.1 sollte der Bug behoben sein aber mir wird die Quest für die XP-Trinkets nicht vorgeschlagen.

**Reproduktion:**
Ich habe einen [Ork (12)](https://imgur.com/C7Vj6kS) & Untoten _„Normal“_ hoch gelvlt aber mir wird keine Quest vorgeschlagen.
Anschließend habe ich noch kurz einen [Menschen (19)](https://imgur.com/oLJkAeF) auf Lvl 19 geboostet aber hier habe ich auch keine Quest bekommen.

**Erwartetes Verhalten:**
Wie oben schon erwähnt sollte jeder Charakter die Quest ab Lvl 10 angeboten bekommen.
