### ISSUE TITLE
Rested EXP scheint nicht mehr richtig zu funktionieren

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#31]
**Fehlerbeschreibung**
Die Rested EXP scheinen nicht mehr richtig zu funktionieren wenn man online ist und in einem Gashthaus sich befindet.
(Vom discord: "Seit dem Restart für die Testbox, gibt es die quest für die exp trinkets nicht mehr. (genauso wenig, wie die schnellere erholt-rate, wenn man eingeloggt ist)")

**Zur Reproduktion**
Gehe in ein Gasthaus und warte dort ob sich die Rested EXP bemerkbar machen auf deiner EXP-Leiste.

**Erwartetes Verhalten**
Sollte sehr schnell gehen und erkenntlich sein, ob die Rested EXP am steigen ist.

**Screenshots**
https://streamable.com/d43wpw

**Comment by Nolin7777** [comment]
Rested XP Boost funktioniert nur noch wenn man sich eingeloggt in einem Gasthaus außerhalb der Hauptstädte befindet!
