### ISSUE TITLE
Teleportations Schriftrollen und Bücher

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#32]
**Beschreibe deinen Vorschlag**
Vorschlag kommt von Wing:
Vielleicht sollten wir Teleportations Schriftrollen und Bücher einbauen.

**Zusätzlicher Kontext**
-

**Comment by SimonMallow** [comment]
Ist damit gemeint, dass man mit diesen Büchern und Schriftrollen sich in der Welt leichter bewegen kann aber als Consumables dann eben auch als  Goldsink dienen?

**Comment by Nolin7777** [comment]
Erstmal nicht. :)
