### ISSUE TITLE
Horned Viking Helmet - auch für Allianzspieler zugänglich machen

### ISSUE THREAD

**Issue by SimonMallow** [HateForge-WoW/Bugtracker#34]
In Classic ist der Horned Viking Helmet (hier ein Link dazu https://www.wowhead.com/classic/item=9394/horned-viking-helmet) nur für Hordespieler zugänglich, da dieser von einem NPC in Uldaman mit dem Namen Eric "The Swift" dropt, welcher der Allianzfraktion engehört.

Meine Frage ist, ob man diesen NPC nicht Fraktionslos gestalten könnte, um die Möglichkeit zu erhalten, diesen zu bekämpfen, um dieses Item zu erhalten.

Warum der Aufwand? Dieses Helm ist ein gängiger Gegenstand im PvP.

**Comment by Bowflinger** [comment]
Kam bis jetzt noch nicht dazu, es zu testen. Aber von anderen mixed-faction servern kenne ich es wie folgt:

1.Horden Charactere bilden eine Gruppe mit allianzlern.
2. Allianzler können nur zugucken, weil die mobs freundlich sind
3. horder töten den mob und looten
4. allianzler können mitwürfeln

Ist zwar keine optimale Lösung, aber falls das hier aufm server auch klappt, wäre es **eine** Lösung,
