### ISSUE TITLE
[LBRS] Endboss droppt manchmal keine items

### ISSUE THREAD

**Issue by Bowflinger** [HateForge-WoW/Bugtracker#35]
**Fehlerbeschreibung**
Der Endboss von LBRS:
https://www.wowhead.com/classic/npc=9568/overlord-wyrmthalak
hat zwei runs in Folge nur die Quest gedroppt, aber kein  einziges grünes/blaues Item.
Wir haben schonmal Loot von ihm bekommen.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. LBRS Endboss killen
2. hoffen(?) , dass er nichts droppt

**Erwartetes Verhalten**
Instanzbosse sollten immer ein grünes/blaues/episches item droppen

**Screenshots**
![no_loot](https://github.com/HateForge-WoW/Bugtracker/assets/142156103/bfd6ef9c-3706-47c5-af3f-9f68ebdf9f87)

**Quellenangabe**
n/a

**Zusätzlicher Kontext**
wir haben ihn ca 6-7 mal getötet und 2x hat er bis auf das quest item nichts gedroppt

**Comment by schell244** [comment]
Loot tables wurden überarbeitet. Danke für den report!
