### ISSUE TITLE
Loot tables sind fehlerhaft

### ISSUE THREAD

**Issue by Bowflinger** [HateForge-WoW/Bugtracker#36]
**Fehlerbeschreibung**
Beim LBRS trash droppt ab und an sehr niedriger Loot (nicht außschließlich, die meisten items stimmen)

Umgekehrt droppen mobs im low level Bereich items, die teilweise mehrere Level über ihrem Level sind.

**Screenshots**

![low_loot](https://github.com/HateForge-WoW/Bugtracker/assets/142156103/5bf92485-06cc-4aa4-8bd6-dde207768ea0)

![high_loot](https://github.com/HateForge-WoW/Bugtracker/assets/142156103/fc10801a-2e3a-45ec-b7e7-98bbad17c44a)

**Comment by Nolin7777** [comment]
Danke für das Ticket, brauchen dazu aber mehr Quellenangaben zu loot, wobei es eher unmöglich ist, den korrekten (Blizzlike) Loot für alle NPCs in Web-Archiven zu finden.
