### ISSUE TITLE
Totemquestreihe (Wasser / Feuer) - Folgequests geben die Fehlermeldung "Ihr erfüllt die Voraussetzungen nicht" bzw. werden nicht angeboten

### ISSUE THREAD

**Issue by JackoRackham** [HateForge-WoW/Bugtracker#39]
Die Questreihen des Wasser- und Feuertotems sind nach der Startquest nicht fortführbar

**Zur Reproduktion**

1. Startquests "Ruf des Wassers" / "Ruf des Feuers" annehmen
2. Startquest beim jeweiligen NPC abgeben
3. Nimmt man die Folgequests (Folgequests 1530 / 1524) direkt an gibt es die o.g. Fehlermeldung, Bricht man den Dialog ab wird die Quest nicht angeboten

**Comment by schell244** [comment]
Danke für den Report! Problem wird mit dem nächsten update gefixed.
