### ISSUE TITLE
NPCs stehen halb im Boden in Northwatch Hold!

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#4]
**Fehlerbeschreibung**
Es stehen einige NPCs so halb im Boden in einen der Türme in Northwatch Hold

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Gehe nach Barrens - Northwatch Hold
2. Gehe in den Turm wie im Video/Screenshot zu sehen ist
3. NPCs stehen halb im Boden.

**Erwartetes Verhalten**
Die NPCs sollten nicht halb im Bodem stehen.

**Screenshots**
Hier ist ein Video dazu:
https://discord.com/channels/@me/1135664217958133881/1140256502431613129
oder https://streamable.com/voxrnf
https://imgur.com/a/QUAoqwb

**Quellenangabe**
-

**Zusätzlicher Kontext**
-

**Comment by Nolin7777** [comment]
Mittlerweile sieht alles normal aus, möglicherweise ein Map-Problem, welches mal nebenbei gefixt wurde.
