### ISSUE TITLE
[Allianz] Ony Pre Quest

### ISSUE THREAD

**Issue by xkingdingelingx** [HateForge-WoW/Bugtracker#41]
**Fehlerbeschreibung**
[Gefängnisausbruch]
Die Fraktions Übergreifende Gruppe führt dazu, dass Marshal Reginald Windsor für Hordler als feindselig gilt, sobalt er sich seine Ausrüstung aus der Kiste holt. Er selber greift zwar nicht an, aber als Hordler kann man den guten angreifen (und auch töten...). Jegliche AoE Interaktionen könnten somit zu Komplikationen führen.

**Erwartetes Verhalten**
NPC bleibt weiterhin freundlich so wie davor auch. Solange er "nackt" rumläuft, bevor er sich seine Ausrüstung holt ist alles gut.

**Quellenangabe**
Keine Quellen, da Server internes Problem (Fraktions übergreifend)

**Zusätzlicher Kontext**
Quest kann trotzdem abgeschlossen werden. Horden Spieler müssten nur extrem aufpassen.

**Comment by schell244** [comment]
Will be fixed with next update :)
