### ISSUE TITLE
[NPC/Quest] NPC klont seine Quests

### ISSUE THREAD

**Issue by Bowflinger** [HateForge-WoW/Bugtracker#43]
**Fehlerbeschreibung**
Der NPC ["Captain Hecklebeury Smotts"](https://www.wowhead.com/classic/npc=2500) hat die Quests, die er gibt
- https://www.wowhead.com/classic/quest=8551/the-captains-chest
- https://www.wowhead.com/classic/quest=8553/the-captains-cutlass
jeweils zweimal zur Auswahl.

Beide Quests können doppelt abgeschlossen werden.
Anders formuliert: Es korrigiert sich NICHT von alleine, wenn man die Quest einmal abschließt. Der "Klon" ist immer noch verfügbar.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Ab nach Booty Bay
2. Mit dem Captain reden
3. Wenn man die zweite Quest auch testen will, muss man kurz den Riesen auf der Insel vor Booty Bay töten und die Quest von seinem Item annehmen.

**Erwartetes Verhalten**
Die beiden Quests sind nur einmal abschließbar, da es keine wiederholbaren Quests sind.

**Screenshots**

![doppel_Quest](https://github.com/HateForge-WoW/Bugtracker/assets/142156103/fa7d786e-066a-4028-8892-c32f226cbfb0)

**Zusätzlicher Kontext**
Quests nur einmal vergeben? [Regeln sind für nicht-Piraten](https://www.youtube.com/watch?v=i8ju_10NkGY)

**Comment by schell244** [comment]
Sollte mit den nächsten update gefixed sein. Danke für den Report!
