### ISSUE TITLE
Broken Tooth benutzt falsche Fähigkeiten

### ISSUE THREAD

**Issue by JackoRackham** [HateForge-WoW/Bugtracker#46]
Beim Zähmen von Broken Tooth ist mir aufgefallen, dass sie die falschen Skills benutzt (siehe Screenshot)

<img width="257" alt="BrokenTooth" src="https://github.com/HateForge-WoW/Bugtracker/assets/120782983/be9a8cfb-2e02-457b-a0de-a3afc6e48648">

**Comment by schell244** [comment]
Broken Tooth is no longer broken. Danke für den Report!
