### ISSUE TITLE
[Pathfinding] Nachtelfen Startgebiet

### ISSUE THREAD

**Issue by Bowflinger** [HateForge-WoW/Bugtracker#48]
**Fehlerbeschreibung**
Die Starterplatform ist für mobs nicht erreichbar.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. nachtelf erstellen
2. Monster pullen

**Erwartetes Verhalten**
Mobs finden einen Weg nach unten.

**Screenshots**

![evade 1](https://github.com/HateForge-WoW/Bugtracker/assets/142156103/c3ae1758-3387-4511-9397-1c5f2e3a42bf)
![evade 3](https://github.com/HateForge-WoW/Bugtracker/assets/142156103/e1986a87-5d0d-4456-b84f-10dd4942e3e1)
![evade 2](https://github.com/HateForge-WoW/Bugtracker/assets/142156103/799df207-5928-468f-bc7e-495cc45be053)

**Zusätzlicher Kontext**
Dürfte, wie in den anderen Fällen, das Pathing sein.

**Comment by JackoRackham** [comment]
Das Problem betrifft nicht nur die Startplattform sondern sehr viele Bereiche Nord Westlich vom "Baum"
