### ISSUE TITLE
[Allianz Quest] Mondlichtung/Moonglade

### ISSUE THREAD

**Issue by xkingdingelingx** [HateForge-WoW/Bugtracker#49]
**Fehlerbeschreibung**
Deutscher Client:
Quest wird beim NPC normal in deutsch angezeigt. Nach dem Annehmen ist der komplette Text im Questlog allerdings auf Englisch.

**Zur Reproduktion**
Druide auf lvl 10 leveln und die Quest bei NPC Mathrengyl Bärenfährte annehmen.

**Erwartetes Verhalten**
Questtext sollte weiterhin in deutsch angezeigt werden.

**Screenshots**
Vor Annehmen der Q:
![TextDE](https://github.com/HateForge-WoW/Bugtracker/assets/142155832/917040ac-e8fc-40f3-ab1f-5596d9ee08e6)
Nach Annehmen der Q:
![TextEN](https://github.com/HateForge-WoW/Bugtracker/assets/142155832/8c702c3f-f360-4151-b0c9-ccff3820d60b)

**Comment by schell244** [comment]
Sollte ein Fehler im quest Addon sein. Addon ausschalten, WDB Ordner löschen und quest nochmal annehmen, dann sollte der detuschen Text im questlog angezeit werden.

**Comment by xkingdingelingx** [comment]
Addons ausgeschaltet hatte ich - Fehler bestand weiter.

Werde das mit dem WDB heut Mittag mal auf 'nem neuen Druiden testen.

**Comment by JackoRackham** [comment]
Kann ich nicht nachstellen, auch nicht mit eingeschalteten Addons:

<img width="372" alt="Mondlichtung1" src="https://github.com/HateForge-WoW/Bugtracker/assets/120782983/3ea2465e-deb4-41c3-8e77-170e0634aaa9">

<img width="724" alt="Mondlichtung2" src="https://github.com/HateForge-WoW/Bugtracker/assets/120782983/c189f7e5-f779-446e-a889-fcf67af799c8">
