### ISSUE TITLE
[Warrior] - Wutgeneration durch eingehenden Schaden arbeitet nicht korrekt

### ISSUE THREAD

**Issue by JackoRackham** [HateForge-WoW/Bugtracker#50]
Durch eingehenden Schaden wird gefühlt nur bei jeder 3ten Attacke Wut generiert.

How to reproduce:

1. Krieger erstellen
2. Im Startgebiet einen Gegner angreifen
3. Attacke stoppen und Wutgeneration beobachten

**Comment by JackoRackham** [comment]
Die genaue Formel wäre dann nach dem Fight Club-Discord
(https://discord.com/channels/383596811517952002/665563022537785344/665593943668293632):
```
conversionFactor = 0.0091107836 * playerLevel² + 3.225598133 * playerLevel + 4.2652911
rageFromDamageTaken = damageTaken / conversionFactor * 2.5
```

**Comment by xkingdingelingx** [comment]
Was genau heißt "Bestätigt" in dem Fall? Verhält sich die Berechnung im low lvl falsch?

Haben das mit Ktc`s 60er Warrie getestet und es war alles korrekt. Auch das mit der Rundung sollte so ja stimmen.

                    Rechnerisch     Tatsächliche Wut
1. Schlag          1,4                         1
2. Schlag          1,4                         1
3. Schlag          1,4                         2 

Nach dem 3. Schlag sollten dann 4,2 Wut gespeichert sein und der Warrie hatte auch 4 Wut zur Veerfügung. Ob aufgerundet wird oder nicht haben wir nicht rausfinden können.
