### ISSUE TITLE
Event-Meldungen , zu viel ?!

### ISSUE THREAD

**Issue by Snoer666** [HateForge-WoW/Bugtracker#51]
Ich weiß nicht genau wo überall Events sein können ist mir in Winter und Un Goro aufgefallen.

In Winterspring und im Un Goro Krater werden Event meldungen gespamt mit zuviel Text .
Dadurch wird der Chat sehr schnell zugespamt und ist schwer nachvollziehbar.

Weiße Meldung sollte nicht im Chat gezeigt werden / sieht nach dem Command für das Event aus 
Rote Event Meldung ist okay
![Screenshot (8)](https://github.com/HateForge-WoW/Bugtracker/assets/145007971/1fe10331-97b1-4d80-a1a1-5a154d2f7cf5)

**Comment by JackoRackham** [comment]
Hast du da irgendeine evtl. Art Debugging aktiv?
Bei mir kommen nur die roten Eventmeldungen:
<img width="405" alt="Chat_Silithus" src="https://github.com/HateForge-WoW/Bugtracker/assets/120782983/219e04ba-d03f-49c3-86b8-961660c27817">

**Comment by Snoer666** [comment]
Nope , und auch nicht wirklich addons . Eventl schon gepatcht ? Das war am Dienstag

**Comment by Snoer666** [comment]
Bevor ich noch n Meldung aufmache wie sieht das bei dir mit HC toden aus ? Bei mir kam diese Meldung 
![Screenshot (10)](https://github.com/HateForge-WoW/Bugtracker/assets/145007971/d74bf998-d8c1-434f-9328-578107821bb5)
