### ISSUE TITLE
Exorcism, Holy Wrath und Turn Undead vom Paladin für alle Ziele anwendbar machen

### ISSUE THREAD

**Issue by SimonMallow** [HateForge-WoW/Bugtracker#52]
Ich schlage vor für den Paladin die drei Fähigkeiten Exorcism, Holy Wrath und Turn Undead auf alle Ziele anwendbar zu machen. Nicht aber diese Inhaltlich ansonsten zu verändern.

Wie hinreichend bekannt ist, leidet der Paladin mit seinen Möglichkeiten des Spielens, unter einer Contentänderung, welche zwei Wochen vor Release von WoW Vanilla umgesetzt wurde, weil zwei neue Entwickler, die zu der Zeit dem Team beitraten, kein Interesse daran hatten, dass Supportklassen viel Schaden machen sollen. Was allerdings dabei herauskam, war eine völlig ungetestete und super langweilige Spielweise.

Im Moment lassen sich diese drei Fähigkeiten nur auf Untote anwenden. Gegen Untote fühlen sich diese Fähigkeiten in ihrer Anwendung ziemlich befriedigend an. Vor allem, wenn man dies an der Zwei-Button-Rotation von Seal und Judgement bemisst. 

Vergleicht man das Fähigkeitenspektrum mit dem Schmanen, welcher mutmaßlig das Gegenstück des Paladin darstellt, verfügt der Paladin über eine klar beschränkte Palette, sowohl im PvE als auch im PvP.

Darum schlage ich vor allen drei Fähigkeiten Exorcism, Holy Wrath und Turn Undead, die Beschränkung auf Untote zu entfernen, sodass der Paladin nützliche Fähigkeiten erhält, die bspw. der Schamane faktisch hat ohne den Manaverbrauch, Cooldowns oder den Schaden zu verändern. Somit bräuchte es keine Balanceanpassungen, die einen durchaus in Teufels Küche bringen können.

Zur Gegenüberstellung eine Darstellung von Exorcism im Vergleich zu Lightning Bolt
Exorcism (Rank 6)
505 -  563 dmg
345 Mana
30 Yard Range
Instant Cast
15 sec cooldown

Lighning Bolt
450 - 501 (Rank 10)
238 Mana
36 Yard Range
2 Sec Cast
0 Cooldown

Beide Spells haben ihren Vorteil und  ihren Nachteil gegenüber den anderen. Lightning Bolt ist günstiger und schwächer, während Exorcism keine Cast-Zeit benötigt aber einen relativ langen Cooldown  hat. Für verbrauchten Manapunkt erhalte ich für Exorcism im Durschnitt 1,54 Schadenspunkte, während es für Lightning Bolt 1,99 Schadenspunkte pro Manapunkt sind. Die Reichweite des teureren und stärkeren Exorcism ist geringer. 

Ähnliche Gedanken könnte man sich zu Holy Wrath machen. Turn Undead wäre eine interessante Fähigkeit für den Paladin mehr Crowd Control auszuüben. Alles in allem wäre der Paladin eine interessantere und nützlichere Klasse. Gerne könnte man die Spells umbenennen. 

Der Vorteil für euch entwickler ist hier aber, dass die Fähigkeiten sich jetzt schon bei den Untoten testen lassen und meiner Spielerfahrung nach den Paladin insofern nicht OP machen, weil sie super teuer sind und dieser entsprechend mehr auf sein Mana aufpassen muss. Aber bspw auch mit Exorcism auch mal ernsthaft pullen kann. Eben jene Fähigkeit nutze ich bspw. auch als Prot Paladin zum antanken.

Bitte Umsetzen, ich glaube, dass das der einfachste und eleganteste Schritt ist aus dem Paladin ein tollere und spannendere Klasse zu machen mit minimalsten Aufwand.

**Comment by xkingdingelingx** [comment]
Direkte Klassenänderungen finde ich schwierig. Ich kanns verstehen, grade da die Hybrid Klassen alle mehr oder weniger Meme Speccs sind. Habe das mit dem Druiden auf Nefarian auch durch... egal was man an Gear (sowohl Bät/Katze/Eule) farmt und Mühe rein steckt man wird im Vergleich zu den anderen Klassen halt nicht wirklich belohnt. Am Ende heilt man dann halt. 
Klar dein Raid kann dich auch als Hybrid mitnehmen, aber meist dann nur 1 Slot und joa... 

Dennoch wäre ich kein Fan davon an den Klassen rum zu schrauben. Am Ende vom Tag möchte ich halt doch Classic/Vanilla WoW spielen und nicht "extrem gemoddetes WoW". Gerne alle NPCs ein bisschen getuned und wegen mir auch neue Inis mit neuen Sets. Über die Boni und optimierte Stats kann man denke ich schon einiges rausholen.

Dazu wird es halt auch diverse Meinungen geben. Die aber natürlich völlig irrelevant sind, da der Wille von unserem großartigen Nolin geschehen mag! ;D

**Comment by SimonMallow** [comment]
Naja du wirst aber am 3. November feststellen, dass es eben doch angepasste Elemente auf dem Server gibt, die ja jetzt schon implementiert sind. Ich werde vermutlich einen Menschenkrieger spielen (insbesondere, wenn es nicht zu den Paladinänderungen käme) und der wird die Rassenfertigkeiten eines Trolles tragen, bis er lvl 60 erreicht und umspeccen wird fast nichts kosten (und das ist ein   g r a v i e r e n d e r   Einschnitt in die Spielweise von WoW Vanilla). 

Der Paladin war zu Release durch seine Veränderungen, die er kurz zuvor erlebt hat eben nicht fertig. Einen Monat vor Release war das eine vollkommen andere Klasse mit Holystrike (sowie Heroic Strike - mit reinem Heiligschaden) und einem bis  zu fünf mal Stackbaren Crusaderstrike. Das wurde entfernt und gegen das sehr  mäßige Seal/Judgement System ersetzt. 

Fazit: Ich schlage nicht vor den Paladin "extrem" krass zu modden, sondern vorhandene Fähigkeiten nicht nur aus Loregründen auf einen Gegnertyp zu beschränken.

**Comment by xkingdingelingx** [comment]
Die angesprochenen Racials gibt es halt genau so im Spiel. Wird halt eher dafür sorgen, dass es Rassentechnisch Abwechslung gibt und jeder die Rasse spielen kann, die ihm optisch am besten gefällt. 
Sehe das also eher nicht als gravierenden change. Zwingt ansonsten halt alle PvE Warries zu Menschen. Jetzt können sie auch als Gnom/Nachtelfe/whatever rum laufen.
Und wenn man das ganze günstig hin und her speccen kann, dann würde ich das unter quality of life einordnen. Wegen mir gerne - würde dem tuning von Encountern engegen kommen, dass die Spieler sich da besser drauf anpassen können.

Also die Werbung, die mich hier her gebracht hat lautete unter anderem: "Entdecke Vanilla WoW neu, angereichert mit frischen Quests, Items, Dungeons und Raids, die das Spielerlebnis spannend und lebendig halten. Unser Ziel ist es, die ursprüngliche Spielatmosphäre und Balance des Classic Plus-Contents zu bewahren und zugleich ein revitalisiertes Spielerlebnis zu ermöglichen."

Kann halt in beide Richtungen verstanden werden: bewahren <-> revitalisierend. 
Man wird sehen in welche Richtung die Reise gehen wird. 

War ja wie gesagt auch nur meine Meinung. Bin sicher du wirst genau so viele Leute finden, die Änderungen, wie du sie vorgeschlagen hast wünschen.

**Comment by SimonMallow** [comment]
Damit kann ich leben.

**Comment by Nolin7777** [comment]
Danke fuer den Vorschlag, wir arbeiten gerade an anderen Methoden um Paladin auch als nicht-heiler spielbar zu machen!
