### ISSUE TITLE
Marshal Windsor Begleitquest in BRD

### ISSUE THREAD

**Issue by SimonMallow** [HateForge-WoW/Bugtracker#53]
Bei den beiden NPCs "Jaz" und "Ograbisi" befielt Windsor die Tür zu öffnen. Normalerweise sollten diese NPCs feindlich sein und getötet werden, sie bleiben aber freundlich und sind somit nicht tötbar.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Gehe zu Begleitquest Windsor für Ony Pre
2. Öffne die Dritte Tür, die Windsor befiehlt.
3. Die NPCs Jaz und Orgabisi sind freundlich statt feindlich

![Begleitquest](https://github.com/HateForge-WoW/Bugtracker/assets/143521488/d40e3e97-e810-4f1d-9762-256dc8e72e67)

**Comment by schell244** [comment]
Ist gefixed. Danke euch!
