### ISSUE TITLE
Unsichtbare Mobs - Magierquest (Allianz): Untersuchungen im Blauen Eremiten 

### ISSUE THREAD

**Issue by Texhon** [HateForge-WoW/Bugtracker#55]
**Fehlerbeschreibung**
Bei Verwendung des Gegenstandes Inkantation der Manifestation (https://www.wowhead.com/classic/de/item=7308/inkantation-der-manifestation) sollte eine Spaltbrut spawnen (Beschwörungsanimation funktioniert nicht). Teilweise spawnen aber zwei und das unsichtbar. Wenn man etwas herumläuft werden die Gegner sichtbar. Zuvor wird man sonst einfach von "Unbekannt" attackiert und nimmt Schaden. 

Der Rest der Quest funktioniert (betäuben, einfangen, Kasten looten).

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Magier sein. 2. Quest "Untersuchungen im Blauen Eremiten" annehmen. 3. Gegenstände vom Tisch mitnehmen. 4. Zur Taverne des Blauen Eremiten in SW gehen. 5. Gegenstand "Inkantation der Manifestation" benutzen.

**Erwartetes Verhalten**
Die Rissbrut sollte mit einer Beschwörungsanimation spawnen und direkt sichtbar sein.

**Screenshots**
Füge gegebenenfalls Screenshots hinzu, um das Problem zu verdeutlichen.

**Quellenangabe**
https://www.youtube.com/watch?v=TvHXFAGzqAY
https://www.youtube.com/watch?v=0k9D8Mp2XbM
https://www.wowhead.com/classic/de/quest=1920/untersuchungen-im-blauen-eremiten#english-comments

**Zusätzlicher Kontext**
Falls vorhanden, füge hier weitere Informationen zum Problem hinzu.

**Comment by schell244** [comment]
Fixed mit dem nächsten update, credits an VMangos. Danke für den Report!
