### ISSUE TITLE
[Hunter - Pet] Growl kostet Trainingspunkte

### ISSUE THREAD

**Issue by Bowflinger** [HateForge-WoW/Bugtracker#56]
**Fehlerbeschreibung**
Die Agrofähigkeit vom Pet  - Growl - sollte ab Patch 1.7 keine Trainingspunkte mehr kosten.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Pet zähmen
2. probieren "growl" beizubringen
3. Schlägt fehl, da "rebellious" pets negative trainingspunkte haben
4. Mit höherer Loyalitätsstufe, wenn das Pet Trainingspunkte hat, noch mal probieren
5. => Growl kostest Trainingspunkte

**Erwartetes Verhalten**
Growl kostet keine Trainingspunkte des Begleiters und kann somit jedem Begleiter direkt und umsonst beigebracht werden. 
Im Beast Training Fenster wird es schon korrekt ohne Kosten angezeigt.

**Quellenangabe**
"Training point costs for all abilities have been rebalanced. You'll now be able to use all your pet's training points with meaningful choices. **To help make "hunting" pets more viable in more situations, the Growl ability is now free to all pets.**"
https://wowpedia.fandom.com/wiki/Patch_1.7.0#Pets

**Screenshots**
Fehlermeldung, beim Versuch es beizubringen:
![Growl_Not_Enough_Points](https://github.com/HateForge-WoW/Bugtracker/assets/142156103/f6c009b7-0482-457e-a665-727e1ed3bd0a)

Einmal vorm Beibringen von Rang 1 (8 Trainingspunkte)
![growl_vorher](https://github.com/HateForge-WoW/Bugtracker/assets/142156103/23826a1c-5707-46c1-842c-74f8330c7f38)

Einmal danach (7 Trainingspunkte)
![growl_nacher](https://github.com/HateForge-WoW/Bugtracker/assets/142156103/13845fd9-1d81-46f0-abc2-7749e0b3e5ef)

**Comment by schell244** [comment]
Fixed, danke für den Report!
