### ISSUE TITLE
[Gnomeregan] Dark Iron Land Mine

### ISSUE THREAD

**Issue by Bowflinger** [HateForge-WoW/Bugtracker#57]
**Fehlerbeschreibung**
Die Mine wird im Countdown nur als "Pet" bezeichnet.

**Erwartetes Verhalten**
Im Chat steht der richtige Name.

**Screenshots**

![mine_wrong_name](https://github.com/HateForge-WoW/Bugtracker/assets/142156103/5b112162-f478-460d-a5c8-76ae1b388247)

**Comment by Nolin7777** [comment]
fixed

**Comment by schell244** [comment]
Fix kommt mit dem nächsten Update. Danke für den Report!
