### ISSUE TITLE
Zu viele Rar Elite im Kloster

### ISSUE THREAD

**Issue by Niwa121** [HateForge-WoW/Bugtracker#59]
Fehlerbeschreibung

In der Instanz Kloster Teil Friedhof spawnen alle drei rar Elite Eisenrücken, Azshir der Schlaflose und Gestürzter Held, an allen möglichen Spawnstandorten, gleichzeitig. 

Zur Reproduktion
Schritte, um das Verhalten zu reproduzieren:

Ich habe mehrmals die Instanz nach einem Reset betreten und immer wieder spawnen die Mobs.

Erwartetes Verhalten
Sie sollten nicht an jeder Stellen und alle gleichzeitig spawnen.

Screenshots

Hier ein paar Beispiele aus einem Instanz durchlauf:

![image](https://github.com/HateForge-WoW/Bugtracker/assets/145850544/8e672a84-b869-4d3f-937e-c54b527a185d)

![image](https://github.com/HateForge-WoW/Bugtracker/assets/145850544/13caed80-51ce-4dc3-8fc5-cd1d17c19a27)

![image](https://github.com/HateForge-WoW/Bugtracker/assets/145850544/c29c0b59-09af-40d4-bf41-09e91d56e0e6)

**Comment by schell244** [comment]
Mit dem nächsten update gefixed. Danke für den report!
