### ISSUE TITLE
Azurelode Mine - man kann manche Vorkommen nicht anklicken als Allianzler (Mining - Filter Faction flagged)!

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#6]
**Fehlerbeschreibung**
Als Allianzler sieht man jede Menge Vorkommen auf der Minikarte aber man kann die meisten Vorkommen nicht abbauen!
Als Horde Charakter kann man dies jedoch ohne Probleme tun.

**Zur Reproduktion**
Als Allianz Charakter mit find Minerals aktiviert in die Azurelode Mine in Hillsbrad Foothills gehen und die Minikarte nachschauen. 
Man könnte auch versuchen durch die Mine zu gehen und dir Vorkommen anzuklicken!

**Erwartetes Verhalten**
Ich persönlich dachte immer das man da auch als Allianzler alles abbauen konnte, aber kann mich irren. 
Ich schreibe diesen Bugreport für g3never vom Hateforge discord!

**Screenshots**
Horde PoV: https://streamable.com/7d9hqa

Allianz PoV: https://streamable.com/rk6lsn 
                   https://streamable.com/g7v2yq
(Mit und ohne GM mode)

**Quellenangabe**

**Zusätzlicher Kontext**
(Schell wollte die Filter Faction Flags nachschauen) :D

**Comment by VincentADK** [comment]
Kleiner Nachtrag: 
Vielleicht auch mal das pooling checken im Alterac Gebirge! :D
(Erinnerung and Schell)

**Comment by schell244** [comment]
Hab es mir angeschaut, das Verhalten ist richtig so. Für Allianz spieler ist diese Mine ein "Safespot", da die NPC's in der Mine Allianz freunlich sind. Somit können dort nur Horde Spieler chests & nodes looten.
