### ISSUE TITLE
Im Arathibecken Sounds vertauscht

### ISSUE THREAD

**Issue by SimonMallow** [HateForge-WoW/Bugtracker#62]
Beim Erobern und Verlieren eines Flaggenpunktes im Arathibecken, sind die Sounds dafür explizit vertauscht. 

Ich meine, dass das Selbe auch für das AV gilt.

Reproduktion
Flagge erobern und Flagge verlieren. Lauschen.

**Comment by schell244** [comment]
Ist tatsächlich absicht. Die Sounds klingen meiner Meinung eher nach einen Score als einer Warnung.
Sprich wenn du als Allianz Spieler die Flagge aufnimmst oder eine Base angreifst kommt jetzt [dieser Sound](https://www.wowhead.com/classic/sound=8174/pvpflagtakenalliance ) und als Horde Spieler kommt [dieser Sound].(https://www.wowhead.com/classic/sound=8212/pvpflagtakenhorde).
