### ISSUE TITLE
Quest doppelt: Der Schatz der Shen'dralar

### ISSUE THREAD

**Issue by Texhon** [HateForge-WoW/Bugtracker#63]
**Fehlerbeschreibung**
Die Quest "Der Schatz der Shen'dralar" (https://www.wowhead.com/classic/de/quest=7877/der-schatz-der-shendralar) erhält man doppelt.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Gehe zu NPC in DB West "Uralte Shen'dralar" (https://www.wowhead.com/classic/de/npc=14358/uralte-shendralar)
2. Quest "Der innere Wahnsinn" annehmen und abschließen
3. Dann ist die Quest "Der Schatz der Shen'dralar" doppelt annehmbar.

**Erwartetes Verhalten**
Die Quest nur 1x zu erhalten

**Screenshots**
Doppelt im Questlog:
![doppeltimlog](https://github.com/HateForge-WoW/Bugtracker/assets/145346967/653654e8-a149-49a0-b35a-a3ffb3132092)

Doppelt abgegeben:
![doppeltabgegeben](https://github.com/HateForge-WoW/Bugtracker/assets/145346967/ea90f10a-cf4c-434a-8787-6fe035c56e25)

**Quellenangabe**
-

**Zusätzlicher Kontext**
-

**Comment by schell244** [comment]
Fixed, danke für den Report!
