### ISSUE TITLE
Debuffslots erhöhen um mehr Spielweisen zu ermöglichen

### ISSUE THREAD

**Issue by JackoRackham** [HateForge-WoW/Bugtracker#64]
Die Anzahl an Debuffslots ist in Classic stark limitiert gewesen (8, ab 1.7 16, erst mit tbc dann 40
(https://vanilla-wow-archive.fandom.com/wiki/Debuff#:~:text=In%20Vanilla%20WoW%20the%20number,important%20debuffs%20getting%20pushed%20off.)

Damit fallen viele Spielweisen komplett unter den Tisch (Affli, Shadow, usw).
Es wäre zu begrüßen, wenn das Debufflimit bereits zu Beginn erhöht wäre.

**Comment by SimonMallow** [comment]
Ich stimme dem zu!

**Comment by Bowflinger** [comment]
Finde es auch eine gute Idee. Gerade in Anbertracht, dass "Meme"-Specs besser gemacht werden sollen.
Ein Shadow brauch 2 slots (Schattenwort schmerz+ gedankenschinden), um schaden zu machen. Und sowohl warlocks als auch shadows wollen Fluch der Schatten + Schattenverbundbarkeit. Wären also schonmal 4 debuffs, um sinnvoll spielen zu können.

Wenn man sich die Vorgehensweise auf Blizzard's Classic und anderen Privatservern anguckt, haben wir in der Community in den letzten Jahren einen Ruck in Richtung Hyper-Optimierung erlebt. Wenn man jedoch zu den 2-3 Jägern, Hexern oder - Gott bewahre - "meme"-spec Spielern gehört, zieht man bei den Debuffs oft den kürzeren. Es lohnt sich raid-dps technisch einfach nicht, einen Debuff Slot zu opfern, um den Schaden von 2-3 Spielern zu erhöhen, wenn man stattdessen 20 Melees oder 10 Mages buffen kann.

Man hat also nicht nur damit zu kämpfen, dass der Spec an sich weniger Schaden macht - oder teilweise gar nicht richtig spielbar ist - , sondern leidet zusätzlich darunter, dass man bei Debuffs "stiefmütterlich" behandelt wird. Und das sogar aus nachvollziehbaren Gründen.

**Comment by Nolin7777** [comment]
Dem wurde intern zugestimmt. Wir arbeiten daran.
Jedoch zum release wird es noch nicht implementiert sein.
