### ISSUE TITLE
[Allianz] Schurken Gift Quest

### ISSUE THREAD

**Issue by Smilez4U** [HateForge-WoW/Bugtracker#65]
**Fehlerbeschreibung**
Die NPC's [Turmwachposten der Defias](https://www.wowhead.com/classic/de/npc=7056/turmwachposten-der-defias) nehmen mit der Schurkenfähigkeit [Meucheln](https://www.wowhead.com/classic/de/spell=53/meucheln) oder [Hinterhalt](https://www.wowhead.com/classic/de/spell=8676/hinterhalt) Schaden wie jeder normale Mob.

**Zur Reproduktion**

1. Starte die Quest [Klavens Turm](https://www.wowhead.com/classic/de/quest=2359/klavens-turm) in Westfall bei den Koordianten 68,70.
2. Stealthe in den Turm und versuche die Mobs zu meucheln.
3. Siehe Fehler

**Erwartetes Verhalten**
[Turmwachposten der Defias](https://www.wowhead.com/classic/de/npc=7056/turmwachposten-der-defias) sollten durch [Meucheln](https://www.wowhead.com/classic/de/spell=53/meucheln) oder [Hinterhalt](https://www.wowhead.com/classic/de/spell=8676/hinterhalt) sofort sterben.
[Ein Kommentar auf Wowhead](https://www.wowhead.com/classic/quest=2359/klavens-tower#comments:id=2954308) bestätigt, dass diese Mobs One Shot Kill von Ambush sind.
Das [Tagebuch](https://www.wowhead.com/classic/de/item=8046/kearnens-tagebuch), welches man mit dieser Quest bekommt, weist darauf hin, dass die Wachen eine Schwäche gegenüber Meucheln und Hinterhalt haben.

**Quellenangabe**
[Kommentar auf Wowhead](https://www.wowhead.com/classic/quest=2359/klavens-tower#comments:id=2954308)
[Tagebuch](https://www.wowhead.com/classic/de/item=8046/kearnens-tagebuch)

**Comment by schell244** [comment]
Fixed, danke für den Report!
