### ISSUE TITLE
Eine Neulings Gilde in die jeder startet

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#66]
Dieser Vorschlag kommt von nn23 von unserem Discord.

**Beschreibe deinen Vorschlag**
Wie wäre es mit einer Neulings Gilde, in der jeder startet?
nn23 fand das ganz toll auf Turtle WoW.

**Zusätzlicher Kontext**
-

**Comment by Nolin7777** [comment]
Vorerst abgelehnt.
