### ISSUE TITLE
Quest: Der vermisste Diplomat 11/16 - Kein Add (Wächter) wenn der Kampf mit einem Stun (Fieser Trick) beginnt

### ISSUE THREAD

**Issue by Texhon** [HateForge-WoW/Bugtracker#67]
**Fehlerbeschreibung**
Die Quest "Der vermisste Diplomat" (11/16) im Sumpfland handelt davon, dass man den NPC "Tapoke "Slim" Jahn" besiegen soll. Bei Beginn der Quest geht dieser in Stealth und verlässt das Gasthaus. Sobald er dieses verlassen hat, wird er angreifbar. Sobald der Kampf beginnt, spawnt ein Wächter Add ("Slims Freund"). Beginnt man den Kampf jedoch als Schurke mit "Fieser Trick" erscheint das Add erst am Ende des Kampfes.

**Zur Reproduktion**
1. Schurke sein
2. Quest der vermisste Diplomat bis 11 von 16 spielen
3. Die Quest annehmen im Gasthaus im Hafen von Menethil von Mikhail annehmen
4. Tapoke "Slim" Jahn außerhalb des Gasthauses angreifen (Opener mit "Fieser Trick" und ohne Stun )

**Erwartetes Verhalten**
Spawn des Adds "Slims Freund" bei Kampfbeginn.

**Screenshots**
Füge gegebenenfalls Screenshots hinzu, um das Problem zu verdeutlichen.

**Quellenangabe**
https://www.wowhead.com/classic/quest=1249/the-missing-diplomat#comments
https://www.youtube.com/watch?v=y1i0QyUYjNY

**Zusätzlicher Kontext**
Falls vorhanden, füge hier weitere Informationen zum Problem hinzu.

**Comment by schell244** [comment]
Ist gefixed, danke für den report!
