### ISSUE TITLE
Keine Crossfraktion(zumindest Gilden)

### ISSUE THREAD

**Issue by Rivox1997** [HateForge-WoW/Bugtracker#68]
Huhu,

ich hab so ein bisschen mein Problem mit dem Crossrealm.

Ich kenne alle Vorteile davon, allerdings gefällt mir da die Blizzlike Version tatsächlicher besser(also die zu Classic).

Es fühlt sich an wie eine Mystische Welt voller Krieg mit zwei verfeindeten Fraktionen.

Crossrealm stört so wie ich finde bisschen die Immersion.

Zumindest würde ich denken Gilden zu trennen so das es das wenigsten Horde und Ally Gilden gibt.

Mir ist schon klar das der Spielerpool beim Crossrealm grösser wird.

Kann man das eventuell eine Umfrage machen?^^

Viele Grüße
Rivox

**Comment by VincentADK** [comment]
Hallo!
Ersteinmal vielen lieben Dank für deinen Vorschalg!
Wir nehmen wirklich jeden Vorschlag sehr ernst und verstehen auch wie du das meinst. 
Jedoch verfolgen wir eine bestimmte Vision und denken das volles Crossfaction sehr gut auf einen PvE Realm passt. 
Es gibt auch andere Projekte die damit wahnsinnig viel Erfolg haben und die meisten Spieler lieben es. 
Man kann ja dennoch Fraktionsspezifische Gilden machen und ich kann mir sehr gut vorstellen das es diese auch hier geben wird. In Schlachtfeldern werden wir jedoch die Fraktionen voneinander trennen, vielleicht ein kleiner Trost. :D
Tut uns wirklich leid deinen Vorschlag abzulehnen, aber wir hoffen das du uns da verstehen kannst!

Vielen lieben Dank!
- das Hateforge Team
