### ISSUE TITLE
Dualspecc

### ISSUE THREAD

**Issue by Rivox1997** [HateForge-WoW/Bugtracker#69]
Hallo,

wie wäre es für so 300 Gold einen Dualspecc wie in Wotlk einzuführen?

Genau das gleiche System wie in Wotlk.

Ich finde das wäre ein gutes Quality of Life change.

**Comment by VincentADK** [comment]
Hey!
Vielen lieben Dank für dein Vorschlag!
Im Moment möchten wir kein Dualspecc anbieten, du wirst aber die Gelegenheit haben das Respecc Token zu verwenden. Das geht auch in Dungeons/Raids etc. Die Möglichkeiten die uns im Moment zur Verfügung stehen lassen eine schöne Blizzlike Implementation leider nicht zu. Tut uns wirklich leid!
