### ISSUE TITLE
Mehr Gold sinks! 

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#7]
**Beschreibe deinen Vorschlag**
(Mehr Gold sinks wegen geringeren respec Kosten usw.)

Ein paar Spieler fragen ob wir planen eine direkte Reisefunktion zu implementieren. 
Vielleicht könnte man dieses erreichen wenn man dem Greifenmeister eine Prämie gibt und der teleportiert einen dann direkt an den gewünschten Flugpunkt!

Es wäre auch cool einen Gambling NPC einzuführen der halt auch schön als Goldsink dienen soll, so kann man auch gut Gold aus dem Spiel nehmen indem der NPC einen 10% cut nimmt oder so in etwa!

Man könnte auch die Reperaturkosten für Leder und Kettenrüstung anziehen, da ja Stoff und Platte am teuersten ist. 
Vielleicht gleich teuer machen.

Vielleich könnten wir auch es so machen, dass man bei Lehrern wie Berufe oder Waffen Lehrern man Skillpunkte ekommen könnte indem man diesen einfach etwas Gold zu schiebt!

Eine andere Idee wäre auch vor Instanzen oder direkt am Start einer Instanz einen NPC zu haben der einen Reagenzien für teuer verkauft oder sogar reparieren kann! Natürlich auch für ein Premium versteht sich! ;)

**Zusätzlicher Kontext**
https://imgur.com/a/J5hQ8Il

**Comment by VincentADK** [comment]
Noch ein Vorschlag von Simon: Transmog. 
Ich bin mir nicht sicher ob wir das richtig implementieren können ohne Patch oder client Modifizierung aber vielleicht mal eine Überlegung wert! :D

**Comment by Nolin7777** [comment]
Werden wir intern diskutieren
