### ISSUE TITLE
Vorschlag: Reduzierung der Abklingzeit Ruhestein

### ISSUE THREAD

**Issue by Texhon** [HateForge-WoW/Bugtracker#70]
**Beschreibe deinen Vorschlag**
Ich schlage vor, die Abklingzeit des Ruhesteins von 60 Minuten auf 30 Minuten zu reduzieren, sofern sich das Umsetzen lässt.
Für alle Nicht-Magier-Spieler etwas mehr qol.

Ansonsten vllt. als goldsink: Verkauf eines verbessten Ruhesteins.

**Zusätzlicher Kontext**
Füge weitere Informationen oder Screenshots zur deinem Vorschlag hier hinzu.

**Comment by Nolin7777** [comment]
Wir haben ein anderes feature implementiert, welches zur Verkürzung der Ruhesteine sorgt. Announcement in kürze.
