### ISSUE TITLE
[NPC] Atalai deathwalker ist nicht gegen Schaden immun

### ISSUE THREAD

**Issue by Bowflinger** [HateForge-WoW/Bugtracker#71]
**Fehlerbeschreibung**
In der Instanz Sunken Temple gibt es im Raum von "Jammal'an the Prophet" Trolle die nach ihrem Tod einen Geist spawnen. 
Dieser [Geist](https://www.wowhead.com/classic/npc=5271/atalai-deathwalker) sollte gegen sämtlichen Schaden immun sein....ist aber durch physischen schaden tötbar.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Sunken Temple betreten
2. Trolle vor Jammal'an töten (Mini-Troll Bosse töten, um das Schild auszumachen)
3. Geister sind gegen physischen Schaden NICHT immun

**Erwartetes Verhalten**
Die Geister sind gegen jeglichen Schaden immun und müssen bis sie despawnen gekitet werden.

**Screenshots**
![not_immune](https://github.com/HateForge-WoW/Bugtracker/assets/142156103/f19def33-091e-4b97-b771-4de23f639740)

**Quellenangabe**
https://www.wowhead.com/classic/npc=5271/atalai-deathwalker

**Comment by schell244** [comment]
Fixed, danke für den Report!
