### ISSUE TITLE
[NPC] Raging Moonkin enraged bei 100% Leben

### ISSUE THREAD

**Issue by Bowflinger** [HateForge-WoW/Bugtracker#72]
**Fehlerbeschreibung**
Der Darkshore Mob "Raging Moonkin" geht direkt beim Pull in den Enrage Modus und macht mehr schaden

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Gehe nach Darkshore östlich von Auberdine (beim roten Kristall)
2. Greif einen Raging Moonkin an
3. Er/Sie/Es rastet direkt aus.

**Erwartetes Verhalten**
Die Moonkins gehen erst bei niedrigen Leben in den Enrage Modus.

**Quellenangabe**
https://www.wowhead.com/classic/npc=10160/raging-moonkin

**Comment by schell244** [comment]
Fixed, danke für den Report!
