### ISSUE TITLE
[Loot] Scourgestones können ohne Anstecknadel gelootet werden

### ISSUE THREAD

**Issue by Bowflinger** [HateForge-WoW/Bugtracker#73]
**Fehlerbeschreibung**
Die Scourgestones:
https://www.wowhead.com/classic/item=12841/invaders-scourgestone
https://www.wowhead.com/classic/item=12843/corruptors-scourgestone
https://www.wowhead.com/classic/item=12840/minions-scourgestone
...droppen ohne das man die Anstecknadel anhat:
https://www.wowhead.com/classic/item=12846/argent-dawn-commission

Getestet in Strat, Scholo, EPL und WPL. Überall konnten die Steine ohne das Trinket gelootet werden.

**Erwartetes Verhalten**
Nur wenn man eine Anstecknadel trägt, darf man die Steine looten, bzw. mit würfeln.

**Screenshots**
![Scourgestone](https://github.com/HateForge-WoW/Bugtracker/assets/142156103/f3326e38-d53d-4f08-aceb-972fb1566f2e)

**Quellenangabe**
Kommentarbereich von https://www.wowhead.com/classic/item=12846/argent-dawn-commission

**Comment by VincentADK** [comment]
Hey, vielen lieben Dank für deinen Bug report!
Könntest du bitte noch einmal testen ob das Problem immer noch da ist?
Ich habe heute getestet und bei mir droppen diese Steine nur wenn ich das Trinket ausgerüstet habe.

**Comment by Bowflinger** [comment]
Nö, sieht so aus, als wäre es gefixed.
