### ISSUE TITLE
Quest: Das Szepter von Celebras

### ISSUE THREAD

**Issue by Texhon** [HateForge-WoW/Bugtracker#74]
**Fehlerbeschreibung**
Die Quest "Das Szepter von Celebras" (https://www.wowhead.com/classic/de/quest=7046/das-szepter-von-celebras) für das Mauradon-Portal wird bei Start automatisch geteilt, sofern die Gruppenmitglieder die Prequest abgeben haben. Jedoch zählt das Ritual nur für denjenigen Spieler, welcher die Quest gestartet hat. Entsprechend kann nur dieser Spieler die Quest abgeben.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Mauradon, starte die Prequest "Legenden von Mauradon" (https://www.wowhead.com/quest=7044/legends-of-maraudon)
2. Beide Spieler geben die Quest im Dungeon ab.
3. Einer der Spieler startet die Quest "Das Szepter von Celebras" und der zweite nimmt die automatisch geteilte Quest an.
4. Ritual wird abgeschlossen und der zweite Spieler muss die Quest abbrechen und den Vorgang wiederholen.

**Erwartetes Verhalten**
Die geteilte Quests für alle Spieler abgeschlossen wird.

**Quellenangabe**
Gesunder Menschenverstand :P sonst macht die Funktion, die Quest automatisch zu teilen, keinen Sinn. So sollte es aussehen:
https://youtu.be/IZiZsZNRNrA?si=kP6Pih5cOCATAi6j&t=4126

**Comment by VincentADK** [comment]
Hallo!
Vielen lieben Dank für deinen Bugreport!
Der Bug sollte nun behoben sein!
Machs gut und viel Spass noch!
