### ISSUE TITLE
[Priester] Racial Change

### ISSUE THREAD

**Issue by xkingdingelingx** [HateForge-WoW/Bugtracker#75]
**Fehlerbeschreibung**
Habe alle Rassen, die Priester spielen können, getestet. Bis auf Nachtelf funktioniert auf den ersten Blick alles reibungslos. Bei Nachtelfen habe ich 2 Varianten beobachtet:

1. Man geht zum NPC sucht sich seine Rasse aus und bekommt die Racials + Priester spezifischen Spells. Soweit so gut. Nach Neustart des Spiels bleiben allerdings nur die Racials übrig und ich habe wieder Rang 1 Elunes Anmut und Rang 1 Sternensplitter im Zauberbuch - nicht mehr die "Spezifischen-Spells" der gewechselten Rasse.

2. Man geht zum NPC sucht sich seine Rasse aus und bekommt NUR die Racials, hat aber nicht die Priester "spezifischen-Spells" im Zauberbuch.

"Workaround" den ich herausgefunden habe: Nach dem Neustart, wenn man nur mit den "Wunsch-Racials", aber mit den Rang 1 Nachtelfen "Spezifischen-Spells" da steht, kann man zu einem Priester Lehrer gehen. Dort lernt man die beiden Spells dann auf max und startet das Spiel erneut neu. Beim wieder einloggen hat man dann die "Wunsch-Racials" und die "Spezifischen-Spells" der gewechselten Rasse.
Beim Verlassen und wieder einloggen beginnt der Kreislauf dann von vorne: Man steht wieder mit Rang 1 Nachtelfen spells da...

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Nachtelf Priest erstellen
2. Auf 60 leveln
3. Ich habe immer extra alle Racials gelernt und gemaxed 
4. Item zum Rassen Change kaufen
5. NPC aufsuchen und Rasse wechseln
6. Spiel verlassen und neu einloggen

**Erwartetes Verhalten**
Denke das wisst ihr besser als ich... ;-P 
Aber ich vermute mal es sollte genau so klappen wie bei den anderen Rassen

**Quellenangabe**
Entfällt hier wohl

**Comment by VincentADK** [comment]
Hey, vielen lieben Dank für deinen Bugreport
Das Problem sollte behoben sein!
Machs gut und viel Spass noch!
