### ISSUE TITLE
[Quest] The stones that bind us

### ISSUE THREAD

**Issue by Bowflinger** [HateForge-WoW/Bugtracker#81]
**Fehlerbeschreibung**
Die Mobs bleiben trotz Aktivierung der binding stones unsterblich, was ein Abschließen der Quest unmöglich macht.

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Quest annehmen (als Allianzler gibt es den ersten Teil im Turm in Burg Nethergrade)
2. Mob zu einem binding stone pullen und low hauen
3. stein benutzen

**Erwartetes Verhalten**
der Mob kann nach Benutzen des binding stones getötet werden,

**Screenshots**
interessanterweise hat der Mob sogar eine Animation ("arme heben" als würde er eine Insignie benutzen), wenn neben ihm ein Stein benutzt wird:

![stone_visual](https://github.com/HateForge-WoW/Bugtracker/assets/142156103/e2939306-ba1a-4e29-b20d-328658ece772)

**Quellenangabe**
Hab es so gemacht, wie wie in den Kommentaren beschrieben :
https://www.wowhead.com/classic/quest=2681/the-stones-that-bind-us

**Comment by schell244** [comment]
Das Problem wurde behoben, credits gehen an vmangos.
