### ISSUE TITLE
Windfury Weapon Duration

### ISSUE THREAD

**Issue by Woina89** [HateForge-WoW/Bugtracker#82]
Schamanen können die Zauber Windfury / Rockbiter / Flametongue / Frostbrand auf ihre Waffen wirken.
Die Zauberdauer beträgt lediglich 5 Minuten.

Ich schlage vor, die Zauberdauer - ähnliche wie die Blessings beim Paladin - auf 60 Minuten zu erhöhen.

**Comment by JackoRackham** [comment]
Das Gegenstück zu den Blessings wären die Totems.
Die Waffenverzauberungen dagegen entsprechen den Siegel, hier ist die Dauer unverändert bei 30 Sekunden.

**Comment by Woina89** [comment]
Da liegst du völlig falsch.
Die Waffenverzauberung wird doch als Schamae nicht gerichtet. Die Mechanik ist eine ganz andere. 

Bei deiner Logik, müsste man es mit Zauberöl/Manaöl vergleichen, was auch 30 Minuten sind.

In TBC waren es auch 30 Minuten.

Paladin Blessings wurden in TBC auch erhöht, was der Anlass war, es auf dem Server hier auch zu erhöhen.

**Comment by JackoRackham** [comment]
Die Blessing betreffen, ebenso wie die Totems andere Spieler, was bei den WaffenVZ nicht der Fall ist.
5 Minuten sind völlig ausreichend für eine WaffenVZ, welche keine zusätzlichen Ressourcen (Buffmats) kostet.
Es macht durchaus einen unterschied ob man alle 5 Minuten seine eine eigene Waffe oder 40 Spieler durchbufft.
Und der kleine Segen hält btw. 30 Minuten, nicht 60.
Auch die Siegel wurden später auf 30 Minuten geändert, in Verbindung mit der Abänderung der Richturteile.

**Comment by Woina89** [comment]
Totems blieben auch in TBC bei 2 min und betreffen nur die Gruppe, keine Änderung.

Blessings wurden in TBC erhöht.
Windfury Weapon wurde in TBC erhöht.

Blessings wurden hier erhöht.
Windfury Weapon also hier auch erhöhen.

Dein Vergleich hinkt, sorry.

**Comment by JackoRackham** [comment]
Sollen andere entscheiden.
Ungetestet ist so eine Änderungen, die bei der PTR-Laufzeit nie aufgefallen ist, suboptimal.

**Comment by Woina89** [comment]
Ja sollen andere entscheiden!

Ich weiß, du bist sauer auf mich, weil ich dich als Offi bei Turtle WiW nicht Arms spielen lassen wollte im Raid. Aber hier aufm Server sind nunmal QoL Änderungen geplant, die v.a. mit TBC kamen, und das ist eine davon.

Ich würde es begrüßen, wenn du zukünftig nicht jeden Kommentar von mir wegen der alten Geschichten runterziehst. Danke.

**Comment by Nolin7777** [comment]
Wurde von 5 min auf 30 min angehoben
