### ISSUE TITLE
Weapon Enhancement Shaman

### ISSUE THREAD

**Issue by Woina89** [HateForge-WoW/Bugtracker#85]
Beim Schamanen haben Totems mit Waffeneffekt (z.B. Flametongue Totem https://www.wowhead.com/classic/spell=16387/flametongue-totem , oder Windfury Totem) keinen Effekt auf die Waffe des Schamanen.
Gleiches gilt für die direkten Casts auf die Waffe, z.B. Windfury Weapon ( https://www.wowhead.com/classic/spell=8232/windfury-weapon )

Andere Totems funktionieren (Manaflut, Healing Stream, Stärke, etc.).

.gm off
.gm untargetable off
-> führen zu keinem anderen Ergebnis

**Comment by schell244** [comment]
Fixed
