### ISSUE TITLE
Hardcore Mode - Paladin Bubble/Ruhestein-Combo unmöglich machen

### ISSUE THREAD

**Issue by SimonMallow** [HateForge-WoW/Bugtracker#86]
Stellt euch mal vor.  Du bist in Stratholme mit einer Gruppe im Hardcore-Modus unterwegs und verkrachst dich mit dem Paladin, der Heiler ist oder eure Gruppe droht zu wipen, könnte aber noch gerettet werden. Aber der Paladin entscheidet einfach infight seine Bubble einzuschalten und den Ruhestein zu nutzen.

PalaBubbleRuhestein combo sollte unmöglich sein im Hardcore-Modus, denn sie ist insofern unbalanciert.

**Comment by Nolin7777** [comment]
Jede Klasse soll seine Spells nutzen koennen, auch in HC.

**Comment by lukzak** [comment]
If every class should get its spells in HC, can we get warlock soulstone and shaman ankh working for HC?
