### ISSUE TITLE
Kaputter Wegpunkt/Pathing in Dolanaar (Ancient Protector) und  Moon Priestress Amara!

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#89]
**Fehlerbeschreibung**
Der Ancient Protector und Moon Priestress Amara! laufen durch das Gasthaus, der Wegpunkt/Pathing scheint kaputt zu sein.

**Zur Reproduktion**
Nach Dolanaar gehen und dem kleinen Bäumchen und der Moon Priestess zuschauen.

**Erwartetes Verhalten**
Sollte nicht durch das Gasthaus laufen und auch nicht knapp dran vorbei.

**Screenshots**
https://imgur.com/a/lgrjG1Z

**Quellenangabe**
-

**Zusätzlicher Kontext**
-

**Comment by schell244** [comment]
Fix kommt mit dem nächsten Update!

**Comment by VincentADK** [comment]
Ist erledigt!
