### ISSUE TITLE
Einen Timer für Schwindende Gelehrtenstein wäre super!

### ISSUE THREAD

**Issue by VincentADK** [HateForge-WoW/Bugtracker#9]
**Beschreibe deinen Vorschlag**
Wäre cool wenn man einen Buff oder einen Timer hätte der anzeigt wann das Trinket (Schwindende Gelehrtenstein) ausläuft!

**Zusätzlicher Kontext**
https://imgur.com/a/yK7SZ78

**Comment by Nolin7777** [comment]
Wir sind leider an Client-Limitations gebunden, daher schwer umsetzbar. Eine Idee wäre ein Community-AddOn dazu.
