### ISSUE TITLE
Fischen ist glitchy/clunky

### ISSUE THREAD

**Issue by Pythol** [HateForge-WoW/Bugtracker#90]
**Fehlerbeschreibung**
Beim Angeln gibt es unstimmigkeiten mit dem Bobber und dem Soundeffekt. Das timing scheint nicht ganz zu stimmen!

**Zur Reproduktion**
Angel ins Wasser werfen.

**Erwartetes Verhalten**
Sollte besser funktionieren.

**Comment by VincentADK** [comment]
Dies ist ein bekanntes Problem mit dem client, da können wir leider nichts machen. Dennoch vielen lieben Dank für deinen Report und wir wünschen dir viel Spass!
