### ISSUE TITLE
Untersuchung im Blauen Eremiten, 2 Magier Q Defekt Allianz.

### ISSUE THREAD

**Issue by GTO0** [HateForge-WoW/Bugtracker#91]
**Fehlerbeschreibung**
Der Q Mob Spaltbrut lässt sich während er betäubt ist nicht mit dem Q Item Truhe mit Verwahrungskästen, einfangen. 

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Gehe in den Keller vom Blauen Eremiten in SW.

3. Klicke auf q-Item Interaktion der Manifestation, Besiege den Mob Spaltbrut und Benutze während er Betäubt ist das Q-Item, Truhe mit Verwahrungskästen. 
4. Siehe Fehler
Der Mob wird nicht eingefangen und das Q Item Gefüllte Verwahrungskästen wird nicht erstellt.

**Erwartetes Verhalten**
Während der Mob im Betäubt ist benutzt man das Item Truhe mit Verwahrungskästen, darauf hin verschwindet der Mob Spaltbrut und das Q Item Gefüllte Verwahrungskästen taucht auf dem Boden auf und kann aufgehoben werden. 

**Screenshots**
Füge gegebenenfalls Screenshots hinzu, um das Problem zu verdeutlichen.

**Quellenangabe**
https://www.youtube.com/watch?v=0k9D8Mp2XbM

**Zusätzlicher Kontext**
Falls vorhanden, füge hier weitere Informationen zum Problem hinzu.

**Comment by schell244** [comment]
Fixed mit dem nächsten update, credits an VMangos. Danke für den Report!
