### ISSUE TITLE
Erfahrung bekommen durch Beruf/Sammelberufe 

### ISSUE THREAD

**Issue by Zabutron** [HateForge-WoW/Bugtracker#95]
Wenn man Beruf wie Kräuterkunde  , Bergbau od.  Angeln , Schmiedekunst od. Alchemie hatt das man einen kleinen haufen Erfahrung bekommt od. bei Kritische Erfolg beim abbauen

**Comment by VincentADK** [comment]
Hallo Zabutron, vielen lieben Dank für dein Vorschlag!

Wir haben diesen intern besprochen und würden dies erst einmal so lassen wie es ist, da es Blizzlike ist für Vanilla/Classic. 
Durch unseren kleinen Gnom solltet ihr euch sehr viel Erfahrung bekommen, gepaart mit der ausgeruhten Erfahrung. 
Dennoch danke ich dir und ich wünsche dir einen schönen Tag!
