### ISSUE TITLE
Item: Senggin Root

### ISSUE THREAD

**Issue by Pythol** [HateForge-WoW/Bugtracker#97]
**Fehlerbeschreibung**
Essen stellt kein Mana wieder her.

**Zur Reproduktion**
Senggin Root essen.

**Erwartetes Verhalten**
Sollte Mana und Leben herstellen.

**Quellenangabe**
https://classicdb.ch/?item=3448

**Comment by schell244** [comment]
Kann das Problem nicht reproduzieren. Funktioniert wie erwartet.
