### ISSUE TITLE
Schurken Angriffe aus Verstohlenheit werden nicht durchgeführt

### ISSUE THREAD

**Issue by Rooxus** [HateForge-WoW/Bugtracker#98]
Ab und zu werden Angriffe aus Verstohlenheit nicht durchgeführt.
Getestet mit Meucheln und Erdrosseln.
Interessanter weise wird auch die Energy nicht verbraucht.

Es scheint mit der Abfrage ob man sich hinter dem Ziel befindet zusammen zu hängen. 
Ich bin noch am testen und stehe jedes mal hinter dem Ziel dennoch schneit die Abfrage ab und an nicht immer zu passen und es kommt die Fehlermeldung das ich mich Hinter dem Ziel befinden muss.

Wenn ich absichtlich vor dem Ziel stehe bleibe ich in Verstohlenheit und bekomme die Fehlermeldung das ich hinter dem Ziel sein muss

**Comment by Rooxus** [comment]
Nach weiteren Tests bin ich mir jetzt sicher das es was mit der Abfrage ob man sich hinter dem Ziel befindet zu tun hat.
Hab ca. 100 Gegner aus Verstohlenheit mit Finsterer Stoß angegriffen und kein einziges mal hat der Angriff nicht funktioniert.

**Comment by schell244** [comment]
Sollte mit dem letzten update gefixed sein. Danke für den Report!

**Comment by Rooxus** [comment]
Mit Erdrosseln besteht das Problem leider immer noch.
Meucheln kann ich gerade nicht testen, habe aktuell keinen Dolch.
