### ISSUE TITLE
Wolf Riding training required to buy Horn of the Dire Wolf mount even when conditions are met

### ISSUE THREAD

**Issue by GMRico** [HateForge-WoW/Bugtracker#99]
**Fehlerbeschreibung**
Users with Wolf Riding Trained, over level 40, and are the Orc race are still unable to buy a specific mount from Kildar in Orgrimmar

Wolf riding requires 2 things:
1. You are level 40
2. You are an Orc
If you are not an orc, you need to be Exalted with Orgrimmar

**Zur Reproduktion**
Schritte, um das Verhalten zu reproduzieren:

1. Go to the NPC [Kildar](https://www.wowhead.com/classic/npc=4752/kildar) as an orc above lvl 40
2. Inspect the available mounts
3. Try to buy the [Horn of the Dire Wolf](https://www.wowhead.com/classic/item=5665/horn-of-the-dire-wolf) after training wolf riding

**Erwartetes Verhalten**
If the user is above level 40, is an orc, and has trained wolf riding they should be eligible to purchase [Horn of the Dire Wolf](https://www.wowhead.com/classic/item=5665/horn-of-the-dire-wolf) 

**Screenshots**
[![image.png](https://i.postimg.cc/qv7HM5SL/image.png)](https://postimg.cc/XptzsQVG)

**Comment by schell244** [comment]
Was confirmed to be an issue due to corruped WDB folder

**Comment by GMRico** [comment]
Awesome thanks @schell244 🙌
